// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

module GenerateProof_bitset_64ns_64ns_6ns_1ns_64_1_1 (sel,din,value,dout);

parameter ADDRWIDTH = 6;
parameter DATAWIDTH = 64;


input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
input value;
output [DATAWIDTH-1:0] dout;

reg [DATAWIDTH-1:0] out_tmp;



always @ (*) begin
    out_tmp = din;
    out_tmp[sel] = |value;
end




assign dout = out_tmp;




endmodule
