-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_ProverCircuitEval is
port (
    ch1_val1 : IN STD_LOGIC_VECTOR (127 downto 0);
    u_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_0_ce0 : OUT STD_LOGIC;
    u_0_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    u_0_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    u_0_we0 : OUT STD_LOGIC;
    u_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_0_ce1 : OUT STD_LOGIC;
    u_0_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    u_0_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
    u_0_we1 : OUT STD_LOGIC;
    u_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_1_ce0 : OUT STD_LOGIC;
    u_1_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    u_1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    u_1_we0 : OUT STD_LOGIC;
    u_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_1_ce1 : OUT STD_LOGIC;
    u_1_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    u_1_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
    u_1_we1 : OUT STD_LOGIC;
    V_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_0_ce0 : OUT STD_LOGIC;
    V_0_d0 : OUT STD_LOGIC_VECTOR (127 downto 0);
    V_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_0_we0 : OUT STD_LOGIC;
    V_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_0_ce1 : OUT STD_LOGIC;
    V_0_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    V_0_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_0_we1 : OUT STD_LOGIC;
    V_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_1_ce0 : OUT STD_LOGIC;
    V_1_d0 : OUT STD_LOGIC_VECTOR (127 downto 0);
    V_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_1_we0 : OUT STD_LOGIC;
    V_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_1_ce1 : OUT STD_LOGIC;
    V_1_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    V_1_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_1_we1 : OUT STD_LOGIC;
    witness_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    circuit_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    d_strm_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    a0_tilde : OUT STD_LOGIC_VECTOR (127 downto 0);
    a1_tilde : OUT STD_LOGIC_VECTOR (127 downto 0);
    proof_strm_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    witness_TVALID : IN STD_LOGIC;
    witness_TREADY : OUT STD_LOGIC;
    circuit_TVALID : IN STD_LOGIC;
    circuit_TREADY : OUT STD_LOGIC;
    d_strm_TVALID : OUT STD_LOGIC;
    d_strm_TREADY : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ch1_val1_ap_vld : IN STD_LOGIC;
    a0_tilde_ap_vld : OUT STD_LOGIC;
    a1_tilde_ap_vld : OUT STD_LOGIC;
    proof_strm_TVALID : OUT STD_LOGIC;
    proof_strm_TREADY : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of GenerateProof_ProverCircuitEval is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_start : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_full_n : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_done : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_continue : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_idle : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_ready : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_out : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_write : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_ce0 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_ce1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_we1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_d1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_ce0 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_ce1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_we1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_d1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_ce0 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_ce1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_we1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_d1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_ce0 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_ce1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_we1 : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_d1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_witness_TREADY : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_circuit_TREADY : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_TVALID : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_cp_din : STD_LOGIC_VECTOR (0 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_cp_write : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a0_strm_din : STD_LOGIC_VECTOR (255 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a0_strm_write : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a1_strm_din : STD_LOGIC_VECTOR (127 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a1_strm_write : STD_LOGIC;
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_return_0 : STD_LOGIC_VECTOR (127 downto 0);
    signal ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_return_1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_channel_done_v_mask : STD_LOGIC;
    signal v_mask_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_v_mask : STD_LOGIC := '0';
    signal ap_sync_channel_write_v_mask : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ToField_U0_ap_start : STD_LOGIC;
    signal ToField_U0_ap_done : STD_LOGIC;
    signal ToField_U0_ap_continue : STD_LOGIC;
    signal ToField_U0_ap_idle : STD_LOGIC;
    signal ToField_U0_ap_ready : STD_LOGIC;
    signal ToField_U0_a1_strm_read : STD_LOGIC;
    signal ToField_U0_a0_strm_read : STD_LOGIC;
    signal ToField_U0_a_strm_din : STD_LOGIC_VECTOR (255 downto 0);
    signal ToField_U0_a_strm_write : STD_LOGIC;
    signal ToField_U0_a_strm_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal ToField_U0_a_strm_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal chal2_U0_ap_start : STD_LOGIC;
    signal chal2_U0_ap_done : STD_LOGIC;
    signal chal2_U0_ap_continue : STD_LOGIC;
    signal chal2_U0_ap_idle : STD_LOGIC;
    signal chal2_U0_ap_ready : STD_LOGIC;
    signal chal2_U0_d_strm_cp_read : STD_LOGIC;
    signal chal2_U0_ch2_strm_din : STD_LOGIC_VECTOR (127 downto 0);
    signal chal2_U0_ch2_strm_write : STD_LOGIC;
    signal aggregate_coef_U0_ap_start : STD_LOGIC;
    signal aggregate_coef_U0_ap_done : STD_LOGIC;
    signal aggregate_coef_U0_ap_continue : STD_LOGIC;
    signal aggregate_coef_U0_ap_idle : STD_LOGIC;
    signal aggregate_coef_U0_ap_ready : STD_LOGIC;
    signal aggregate_coef_U0_a_strm_read : STD_LOGIC;
    signal aggregate_coef_U0_ch2_strm_read : STD_LOGIC;
    signal aggregate_coef_U0_a0_tilde : STD_LOGIC_VECTOR (127 downto 0);
    signal aggregate_coef_U0_a0_tilde_ap_vld : STD_LOGIC;
    signal aggregate_coef_U0_a1_tilde : STD_LOGIC_VECTOR (127 downto 0);
    signal aggregate_coef_U0_a1_tilde_ap_vld : STD_LOGIC;
    signal aggregate_coef_U0_proof_strm_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal aggregate_coef_U0_proof_strm_TVALID : STD_LOGIC;
    signal d_strm_cp_full_n : STD_LOGIC;
    signal d_strm_cp_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal d_strm_cp_empty_n : STD_LOGIC;
    signal d_strm_cp_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal d_strm_cp_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal a0_strm_full_n : STD_LOGIC;
    signal a0_strm_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal a0_strm_empty_n : STD_LOGIC;
    signal a0_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal a0_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal a1_strm_full_n : STD_LOGIC;
    signal a1_strm_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal a1_strm_empty_n : STD_LOGIC;
    signal a1_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal a1_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal u_mask_full_n : STD_LOGIC;
    signal u_mask_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal u_mask_empty_n : STD_LOGIC;
    signal u_mask_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal u_mask_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal v_mask_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal v_mask_empty_n : STD_LOGIC;
    signal v_mask_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal v_mask_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal a_strm_full_n : STD_LOGIC;
    signal a_strm_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal a_strm_empty_n : STD_LOGIC;
    signal a_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal a_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ch2_strm_full_n : STD_LOGIC;
    signal ch2_strm_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal ch2_strm_empty_n : STD_LOGIC;
    signal ch2_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal ch2_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sync_done : STD_LOGIC;
    signal start_for_ToField_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_ToField_U0_full_n : STD_LOGIC;
    signal start_for_ToField_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_ToField_U0_empty_n : STD_LOGIC;
    signal start_for_chal2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_chal2_U0_full_n : STD_LOGIC;
    signal start_for_chal2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_chal2_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GenerateProof_ProverCircuitEval_Block_entry_u_0_arg_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        u_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_0_ce0 : OUT STD_LOGIC;
        u_0_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        u_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_0_ce1 : OUT STD_LOGIC;
        u_0_we1 : OUT STD_LOGIC;
        u_0_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        u_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_1_ce0 : OUT STD_LOGIC;
        u_1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        u_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_1_ce1 : OUT STD_LOGIC;
        u_1_we1 : OUT STD_LOGIC;
        u_1_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        V_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_0_ce0 : OUT STD_LOGIC;
        V_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        V_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_0_ce1 : OUT STD_LOGIC;
        V_0_we1 : OUT STD_LOGIC;
        V_0_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
        V_0_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
        V_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_1_ce0 : OUT STD_LOGIC;
        V_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        V_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_1_ce1 : OUT STD_LOGIC;
        V_1_we1 : OUT STD_LOGIC;
        V_1_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
        V_1_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
        witness_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        witness_TVALID : IN STD_LOGIC;
        witness_TREADY : OUT STD_LOGIC;
        circuit_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        circuit_TVALID : IN STD_LOGIC;
        circuit_TREADY : OUT STD_LOGIC;
        d_strm_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        d_strm_TVALID : OUT STD_LOGIC;
        d_strm_TREADY : IN STD_LOGIC;
        d_strm_cp_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        d_strm_cp_full_n : IN STD_LOGIC;
        d_strm_cp_write : OUT STD_LOGIC;
        d_strm_cp_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        d_strm_cp_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        a0_strm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        a0_strm_full_n : IN STD_LOGIC;
        a0_strm_write : OUT STD_LOGIC;
        a0_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        a0_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        a1_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        a1_strm_full_n : IN STD_LOGIC;
        a1_strm_write : OUT STD_LOGIC;
        a1_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        a1_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component GenerateProof_ToField IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        a1_strm_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        a1_strm_empty_n : IN STD_LOGIC;
        a1_strm_read : OUT STD_LOGIC;
        a1_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        a1_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        a0_strm_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        a0_strm_empty_n : IN STD_LOGIC;
        a0_strm_read : OUT STD_LOGIC;
        a0_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        a0_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        a_strm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        a_strm_full_n : IN STD_LOGIC;
        a_strm_write : OUT STD_LOGIC;
        a_strm_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        a_strm_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component GenerateProof_chal2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d_strm_cp_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        d_strm_cp_empty_n : IN STD_LOGIC;
        d_strm_cp_read : OUT STD_LOGIC;
        d_strm_cp_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        d_strm_cp_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ch1_val : IN STD_LOGIC_VECTOR (127 downto 0);
        ch2_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        ch2_strm_full_n : IN STD_LOGIC;
        ch2_strm_write : OUT STD_LOGIC;
        ch2_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ch2_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component GenerateProof_aggregate_coef IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (127 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (127 downto 0);
        a_strm_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        a_strm_empty_n : IN STD_LOGIC;
        a_strm_read : OUT STD_LOGIC;
        a_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        a_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ch2_strm_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        ch2_strm_empty_n : IN STD_LOGIC;
        ch2_strm_read : OUT STD_LOGIC;
        ch2_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ch2_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        a0_tilde : OUT STD_LOGIC_VECTOR (127 downto 0);
        a0_tilde_ap_vld : OUT STD_LOGIC;
        a1_tilde : OUT STD_LOGIC_VECTOR (127 downto 0);
        a1_tilde_ap_vld : OUT STD_LOGIC;
        proof_strm_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        proof_strm_TVALID : OUT STD_LOGIC;
        proof_strm_TREADY : IN STD_LOGIC );
    end component;


    component GenerateProof_fifo_w1_d2_S_x2 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component GenerateProof_fifo_w256_d2_S_x2 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (255 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (255 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component GenerateProof_fifo_w128_d2_S_x3 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component GenerateProof_fifo_w128_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component GenerateProof_start_for_ToField_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component GenerateProof_start_for_chal2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    ProverCircuitEval_Block_entry_u_0_arg_proc_U0 : component GenerateProof_ProverCircuitEval_Block_entry_u_0_arg_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_start,
        start_full_n => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_full_n,
        ap_done => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_done,
        ap_continue => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_continue,
        ap_idle => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_idle,
        ap_ready => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_ready,
        start_out => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_out,
        start_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_write,
        u_0_address0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_address0,
        u_0_ce0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_ce0,
        u_0_q0 => u_0_q0,
        u_0_address1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_address1,
        u_0_ce1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_ce1,
        u_0_we1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_we1,
        u_0_d1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_d1,
        u_1_address0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_address0,
        u_1_ce0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_ce0,
        u_1_q0 => u_1_q0,
        u_1_address1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_address1,
        u_1_ce1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_ce1,
        u_1_we1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_we1,
        u_1_d1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_d1,
        V_0_address0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_address0,
        V_0_ce0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_ce0,
        V_0_q0 => V_0_q0,
        V_0_address1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_address1,
        V_0_ce1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_ce1,
        V_0_we1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_we1,
        V_0_d1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_d1,
        V_0_q1 => V_0_q1,
        V_1_address0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_address0,
        V_1_ce0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_ce0,
        V_1_q0 => V_1_q0,
        V_1_address1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_address1,
        V_1_ce1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_ce1,
        V_1_we1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_we1,
        V_1_d1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_d1,
        V_1_q1 => V_1_q1,
        witness_TDATA => witness_TDATA,
        witness_TVALID => witness_TVALID,
        witness_TREADY => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_witness_TREADY,
        circuit_TDATA => circuit_TDATA,
        circuit_TVALID => circuit_TVALID,
        circuit_TREADY => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_circuit_TREADY,
        d_strm_TDATA => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_TDATA,
        d_strm_TVALID => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_TVALID,
        d_strm_TREADY => d_strm_TREADY,
        d_strm_cp_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_cp_din,
        d_strm_cp_full_n => d_strm_cp_full_n,
        d_strm_cp_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_cp_write,
        d_strm_cp_num_data_valid => d_strm_cp_num_data_valid,
        d_strm_cp_fifo_cap => d_strm_cp_fifo_cap,
        a0_strm_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a0_strm_din,
        a0_strm_full_n => a0_strm_full_n,
        a0_strm_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a0_strm_write,
        a0_strm_num_data_valid => a0_strm_num_data_valid,
        a0_strm_fifo_cap => a0_strm_fifo_cap,
        a1_strm_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a1_strm_din,
        a1_strm_full_n => a1_strm_full_n,
        a1_strm_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a1_strm_write,
        a1_strm_num_data_valid => a1_strm_num_data_valid,
        a1_strm_fifo_cap => a1_strm_fifo_cap,
        ap_return_0 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_return_0,
        ap_return_1 => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_return_1);

    ToField_U0 : component GenerateProof_ToField
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ToField_U0_ap_start,
        ap_done => ToField_U0_ap_done,
        ap_continue => ToField_U0_ap_continue,
        ap_idle => ToField_U0_ap_idle,
        ap_ready => ToField_U0_ap_ready,
        a1_strm_dout => a1_strm_dout,
        a1_strm_empty_n => a1_strm_empty_n,
        a1_strm_read => ToField_U0_a1_strm_read,
        a1_strm_num_data_valid => a1_strm_num_data_valid,
        a1_strm_fifo_cap => a1_strm_fifo_cap,
        a0_strm_dout => a0_strm_dout,
        a0_strm_empty_n => a0_strm_empty_n,
        a0_strm_read => ToField_U0_a0_strm_read,
        a0_strm_num_data_valid => a0_strm_num_data_valid,
        a0_strm_fifo_cap => a0_strm_fifo_cap,
        a_strm_din => ToField_U0_a_strm_din,
        a_strm_full_n => a_strm_full_n,
        a_strm_write => ToField_U0_a_strm_write,
        a_strm_num_data_valid => ToField_U0_a_strm_num_data_valid,
        a_strm_fifo_cap => ToField_U0_a_strm_fifo_cap);

    chal2_U0 : component GenerateProof_chal2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => chal2_U0_ap_start,
        ap_done => chal2_U0_ap_done,
        ap_continue => chal2_U0_ap_continue,
        ap_idle => chal2_U0_ap_idle,
        ap_ready => chal2_U0_ap_ready,
        d_strm_cp_dout => d_strm_cp_dout,
        d_strm_cp_empty_n => d_strm_cp_empty_n,
        d_strm_cp_read => chal2_U0_d_strm_cp_read,
        d_strm_cp_num_data_valid => d_strm_cp_num_data_valid,
        d_strm_cp_fifo_cap => d_strm_cp_fifo_cap,
        ch1_val => ch1_val1,
        ch2_strm_din => chal2_U0_ch2_strm_din,
        ch2_strm_full_n => ch2_strm_full_n,
        ch2_strm_write => chal2_U0_ch2_strm_write,
        ch2_strm_num_data_valid => ch2_strm_num_data_valid,
        ch2_strm_fifo_cap => ch2_strm_fifo_cap);

    aggregate_coef_U0 : component GenerateProof_aggregate_coef
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => aggregate_coef_U0_ap_start,
        ap_done => aggregate_coef_U0_ap_done,
        ap_continue => aggregate_coef_U0_ap_continue,
        ap_idle => aggregate_coef_U0_ap_idle,
        ap_ready => aggregate_coef_U0_ap_ready,
        p_read => u_mask_dout,
        p_read1 => v_mask_dout,
        a_strm_dout => a_strm_dout,
        a_strm_empty_n => a_strm_empty_n,
        a_strm_read => aggregate_coef_U0_a_strm_read,
        a_strm_num_data_valid => a_strm_num_data_valid,
        a_strm_fifo_cap => a_strm_fifo_cap,
        ch2_strm_dout => ch2_strm_dout,
        ch2_strm_empty_n => ch2_strm_empty_n,
        ch2_strm_read => aggregate_coef_U0_ch2_strm_read,
        ch2_strm_num_data_valid => ch2_strm_num_data_valid,
        ch2_strm_fifo_cap => ch2_strm_fifo_cap,
        a0_tilde => aggregate_coef_U0_a0_tilde,
        a0_tilde_ap_vld => aggregate_coef_U0_a0_tilde_ap_vld,
        a1_tilde => aggregate_coef_U0_a1_tilde,
        a1_tilde_ap_vld => aggregate_coef_U0_a1_tilde_ap_vld,
        proof_strm_TDATA => aggregate_coef_U0_proof_strm_TDATA,
        proof_strm_TVALID => aggregate_coef_U0_proof_strm_TVALID,
        proof_strm_TREADY => proof_strm_TREADY);

    d_strm_cp_U : component GenerateProof_fifo_w1_d2_S_x2
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_cp_din,
        if_full_n => d_strm_cp_full_n,
        if_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_cp_write,
        if_dout => d_strm_cp_dout,
        if_empty_n => d_strm_cp_empty_n,
        if_read => chal2_U0_d_strm_cp_read,
        if_num_data_valid => d_strm_cp_num_data_valid,
        if_fifo_cap => d_strm_cp_fifo_cap);

    a0_strm_U : component GenerateProof_fifo_w256_d2_S_x2
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a0_strm_din,
        if_full_n => a0_strm_full_n,
        if_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a0_strm_write,
        if_dout => a0_strm_dout,
        if_empty_n => a0_strm_empty_n,
        if_read => ToField_U0_a0_strm_read,
        if_num_data_valid => a0_strm_num_data_valid,
        if_fifo_cap => a0_strm_fifo_cap);

    a1_strm_U : component GenerateProof_fifo_w128_d2_S_x3
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a1_strm_din,
        if_full_n => a1_strm_full_n,
        if_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_a1_strm_write,
        if_dout => a1_strm_dout,
        if_empty_n => a1_strm_empty_n,
        if_read => ToField_U0_a1_strm_read,
        if_num_data_valid => a1_strm_num_data_valid,
        if_fifo_cap => a1_strm_fifo_cap);

    u_mask_U : component GenerateProof_fifo_w128_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_return_0,
        if_full_n => u_mask_full_n,
        if_write => ap_channel_done_v_mask,
        if_dout => u_mask_dout,
        if_empty_n => u_mask_empty_n,
        if_read => aggregate_coef_U0_ap_ready,
        if_num_data_valid => u_mask_num_data_valid,
        if_fifo_cap => u_mask_fifo_cap);

    v_mask_U : component GenerateProof_fifo_w128_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_return_1,
        if_full_n => v_mask_full_n,
        if_write => ap_channel_done_v_mask,
        if_dout => v_mask_dout,
        if_empty_n => v_mask_empty_n,
        if_read => aggregate_coef_U0_ap_ready,
        if_num_data_valid => v_mask_num_data_valid,
        if_fifo_cap => v_mask_fifo_cap);

    a_strm_U : component GenerateProof_fifo_w256_d2_S_x2
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => ToField_U0_a_strm_din,
        if_full_n => a_strm_full_n,
        if_write => ToField_U0_a_strm_write,
        if_dout => a_strm_dout,
        if_empty_n => a_strm_empty_n,
        if_read => aggregate_coef_U0_a_strm_read,
        if_num_data_valid => a_strm_num_data_valid,
        if_fifo_cap => a_strm_fifo_cap);

    ch2_strm_U : component GenerateProof_fifo_w128_d2_S_x3
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => chal2_U0_ch2_strm_din,
        if_full_n => ch2_strm_full_n,
        if_write => chal2_U0_ch2_strm_write,
        if_dout => ch2_strm_dout,
        if_empty_n => ch2_strm_empty_n,
        if_read => aggregate_coef_U0_ch2_strm_read,
        if_num_data_valid => ch2_strm_num_data_valid,
        if_fifo_cap => ch2_strm_fifo_cap);

    start_for_ToField_U0_U : component GenerateProof_start_for_ToField_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_ToField_U0_din,
        if_full_n => start_for_ToField_U0_full_n,
        if_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_write,
        if_dout => start_for_ToField_U0_dout,
        if_empty_n => start_for_ToField_U0_empty_n,
        if_read => ToField_U0_ap_ready);

    start_for_chal2_U0_U : component GenerateProof_start_for_chal2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_chal2_U0_din,
        if_full_n => start_for_chal2_U0_full_n,
        if_write => ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_write,
        if_dout => start_for_chal2_U0_dout,
        if_empty_n => start_for_chal2_U0_empty_n,
        if_read => chal2_U0_ap_ready);





    ap_sync_reg_channel_write_v_mask_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_v_mask <= ap_const_logic_0;
            else
                if (((ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_done and ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_v_mask <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_v_mask <= ap_sync_channel_write_v_mask;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_done_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_sync_done <= (not(ap_sync_continue) and aggregate_coef_U0_ap_done and ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_done);
        end if;
    end process;
    ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_continue <= (ap_sync_continue and ap_sync_channel_write_v_mask);
    ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_start <= ap_start;
    ProverCircuitEval_Block_entry_u_0_arg_proc_U0_start_full_n <= (start_for_chal2_U0_full_n and start_for_ToField_U0_full_n);
    ToField_U0_a_strm_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(a_strm_fifo_cap),3))),32));
    ToField_U0_a_strm_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(a_strm_num_data_valid),3))),32));
    ToField_U0_ap_continue <= ap_const_logic_1;
    ToField_U0_ap_start <= start_for_ToField_U0_empty_n;
    V_0_address0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_address0;
    V_0_address1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_address1;
    V_0_ce0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_ce0;
    V_0_ce1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_ce1;
    V_0_d0 <= ap_const_lv128_lc_1;
    V_0_d1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_d1;
    V_0_we0 <= ap_const_logic_0;
    V_0_we1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_0_we1;
    V_1_address0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_address0;
    V_1_address1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_address1;
    V_1_ce0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_ce0;
    V_1_ce1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_ce1;
    V_1_d0 <= ap_const_lv128_lc_1;
    V_1_d1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_d1;
    V_1_we0 <= ap_const_logic_0;
    V_1_we1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_V_1_we1;
    a0_tilde <= aggregate_coef_U0_a0_tilde;
    a0_tilde_ap_vld <= aggregate_coef_U0_a0_tilde_ap_vld;
    a1_tilde <= aggregate_coef_U0_a1_tilde;
    a1_tilde_ap_vld <= aggregate_coef_U0_a1_tilde_ap_vld;
    aggregate_coef_U0_ap_continue <= ap_sync_continue;
    aggregate_coef_U0_ap_start <= u_mask_empty_n;
    ap_channel_done_v_mask <= ((ap_sync_reg_channel_write_v_mask xor ap_const_logic_1) and ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_done);
    ap_done <= ap_sync_done;
    ap_idle <= ((u_mask_empty_n xor ap_const_logic_1) and chal2_U0_ap_idle and aggregate_coef_U0_ap_idle and ToField_U0_ap_idle and ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_idle);
    ap_ready <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_ap_ready;
    ap_sync_channel_write_v_mask <= ((v_mask_full_n and ap_channel_done_v_mask) or ap_sync_reg_channel_write_v_mask);
    ap_sync_continue <= (ap_sync_done and ap_continue);
    chal2_U0_ap_continue <= ap_const_logic_1;
    chal2_U0_ap_start <= start_for_chal2_U0_empty_n;
    circuit_TREADY <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_circuit_TREADY;
    d_strm_TDATA <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_TDATA;
    d_strm_TVALID <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_d_strm_TVALID;
    proof_strm_TDATA <= aggregate_coef_U0_proof_strm_TDATA;
    proof_strm_TVALID <= aggregate_coef_U0_proof_strm_TVALID;
    start_for_ToField_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_chal2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    u_0_address0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_address0;
    u_0_address1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_address1;
    u_0_ce0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_ce0;
    u_0_ce1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_ce1;
    u_0_d0 <= ap_const_lv1_0;
    u_0_d1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_d1;
    u_0_we0 <= ap_const_logic_0;
    u_0_we1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_0_we1;
    u_1_address0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_address0;
    u_1_address1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_address1;
    u_1_ce0 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_ce0;
    u_1_ce1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_ce1;
    u_1_d0 <= ap_const_lv1_0;
    u_1_d1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_d1;
    u_1_we0 <= ap_const_logic_0;
    u_1_we1 <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_u_1_we1;
    witness_TREADY <= ProverCircuitEval_Block_entry_u_0_arg_proc_U0_witness_TREADY;
end behav;
