-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_GFMul2 is
port (
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of GenerateProof_GFMul2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal a_2_fu_26_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_18_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_1_fu_32_p2 : STD_LOGIC_VECTOR (7 downto 0);


begin



    a_1_fu_32_p2 <= (ap_const_lv8_1B xor a_2_fu_26_p2);
    a_2_fu_26_p2 <= std_logic_vector(shift_left(unsigned(a),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    ap_ready <= ap_const_logic_1;
    ap_return <= 
        a_1_fu_32_p2 when (tmp_fu_18_p3(0) = '1') else 
        a_2_fu_26_p2;
    tmp_fu_18_p3 <= a(7 downto 7);
end behav;
