-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_compute_mask is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    u_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_0_ce0 : OUT STD_LOGIC;
    u_0_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    u_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_1_ce0 : OUT STD_LOGIC;
    u_1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    V_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_0_ce0 : OUT STD_LOGIC;
    V_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_1_ce0 : OUT STD_LOGIC;
    V_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of GenerateProof_compute_mask is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_110 : STD_LOGIC_VECTOR (8 downto 0) := "100010000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv16_9C41 : STD_LOGIC_VECTOR (15 downto 0) := "1001110001000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_13_reg_254 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln76_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ur_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal ur_ce0 : STD_LOGIC;
    signal ur_q0 : STD_LOGIC_VECTOR (127 downto 0);
    signal Vr_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal Vr_ce0 : STD_LOGIC;
    signal Vr_q0 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_combineVOLEs_fu_142_ap_start : STD_LOGIC;
    signal grp_combineVOLEs_fu_142_ap_done : STD_LOGIC;
    signal grp_combineVOLEs_fu_142_ap_idle : STD_LOGIC;
    signal grp_combineVOLEs_fu_142_ap_ready : STD_LOGIC;
    signal grp_combineVOLEs_fu_142_vals_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_combineVOLEs_fu_142_vals_ce0 : STD_LOGIC;
    signal grp_combineVOLEs_fu_142_ap_return : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_combineVOLEs_fu_147_ap_start : STD_LOGIC;
    signal grp_combineVOLEs_fu_147_ap_done : STD_LOGIC;
    signal grp_combineVOLEs_fu_147_ap_idle : STD_LOGIC;
    signal grp_combineVOLEs_fu_147_ap_ready : STD_LOGIC;
    signal grp_combineVOLEs_fu_147_vals_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_combineVOLEs_fu_147_vals_ce0 : STD_LOGIC;
    signal grp_combineVOLEs_fu_147_ap_return : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_combineVOLEs_fu_142_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_combineVOLEs_fu_147_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln78_1_fu_192_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln76_fu_205_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_54 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln76_fu_166_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal u_0_ce0_local : STD_LOGIC;
    signal u_1_ce0_local : STD_LOGIC;
    signal V_0_ce0_local : STD_LOGIC;
    signal V_1_ce0_local : STD_LOGIC;
    signal ur_we0_local : STD_LOGIC;
    signal zext_ln78_fu_221_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ur_ce0_local : STD_LOGIC;
    signal Vr_we0_local : STD_LOGIC;
    signal select_ln79_fu_226_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal Vr_ce0_local : STD_LOGIC;
    signal zext_ln76_1_fu_172_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln78_fu_176_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln_fu_182_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln76_fu_210_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln78_fu_213_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_return_1_preg : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GenerateProof_combineVOLEs IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vals_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        vals_ce0 : OUT STD_LOGIC;
        vals_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component GenerateProof_compute_mask_ur_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (127 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;



begin
    ur_U : component GenerateProof_compute_mask_ur_RAM_AUTO_1R1W
    generic map (
        DataWidth => 128,
        AddressRange => 272,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ur_address0,
        ce0 => ur_ce0,
        we0 => ur_we0_local,
        d0 => zext_ln78_fu_221_p1,
        q0 => ur_q0);

    Vr_U : component GenerateProof_compute_mask_ur_RAM_AUTO_1R1W
    generic map (
        DataWidth => 128,
        AddressRange => 272,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Vr_address0,
        ce0 => Vr_ce0,
        we0 => Vr_we0_local,
        d0 => select_ln79_fu_226_p3,
        q0 => Vr_q0);

    grp_combineVOLEs_fu_142 : component GenerateProof_combineVOLEs
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_combineVOLEs_fu_142_ap_start,
        ap_done => grp_combineVOLEs_fu_142_ap_done,
        ap_idle => grp_combineVOLEs_fu_142_ap_idle,
        ap_ready => grp_combineVOLEs_fu_142_ap_ready,
        vals_address0 => grp_combineVOLEs_fu_142_vals_address0,
        vals_ce0 => grp_combineVOLEs_fu_142_vals_ce0,
        vals_q0 => ur_q0,
        ap_return => grp_combineVOLEs_fu_142_ap_return);

    grp_combineVOLEs_fu_147 : component GenerateProof_combineVOLEs
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_combineVOLEs_fu_147_ap_start,
        ap_done => grp_combineVOLEs_fu_147_ap_done,
        ap_idle => grp_combineVOLEs_fu_147_ap_idle,
        ap_ready => grp_combineVOLEs_fu_147_ap_ready,
        vals_address0 => grp_combineVOLEs_fu_147_vals_address0,
        vals_ce0 => grp_combineVOLEs_fu_147_vals_ce0,
        vals_q0 => Vr_q0,
        ap_return => grp_combineVOLEs_fu_147_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv128_lc_1;
            else
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_return_0_preg <= grp_combineVOLEs_fu_142_ap_return;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv128_lc_1;
            else
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_return_1_preg <= grp_combineVOLEs_fu_147_ap_return;
                end if; 
            end if;
        end if;
    end process;


    grp_combineVOLEs_fu_142_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_combineVOLEs_fu_142_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_combineVOLEs_fu_142_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_combineVOLEs_fu_142_ap_ready = ap_const_logic_1)) then 
                    grp_combineVOLEs_fu_142_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_combineVOLEs_fu_147_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_combineVOLEs_fu_147_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_combineVOLEs_fu_147_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_combineVOLEs_fu_147_ap_ready = ap_const_logic_1)) then 
                    grp_combineVOLEs_fu_147_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_54 <= ap_const_lv9_0;
            elsif (((icmp_ln76_fu_160_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_fu_54 <= add_ln76_fu_166_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_13_reg_254 <= i_fu_54;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln76_fu_160_p2, ap_enable_reg_pp0_iter1, ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln76_fu_160_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((icmp_ln76_fu_160_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    V_0_address0 <= zext_ln78_1_fu_192_p1(18 - 1 downto 0);
    V_0_ce0 <= V_0_ce0_local;

    V_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            V_0_ce0_local <= ap_const_logic_1;
        else 
            V_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    V_1_address0 <= zext_ln78_1_fu_192_p1(18 - 1 downto 0);
    V_1_ce0 <= V_1_ce0_local;

    V_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            V_1_ce0_local <= ap_const_logic_1;
        else 
            V_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    Vr_address0_assign_proc : process(grp_combineVOLEs_fu_147_vals_address0, ap_CS_fsm_state5, zext_ln76_fu_205_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            Vr_address0 <= grp_combineVOLEs_fu_147_vals_address0;
        else 
            Vr_address0 <= zext_ln76_fu_205_p1(9 - 1 downto 0);
        end if; 
    end process;


    Vr_ce0_assign_proc : process(grp_combineVOLEs_fu_147_vals_ce0, ap_CS_fsm_state5, Vr_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            Vr_ce0 <= grp_combineVOLEs_fu_147_vals_ce0;
        else 
            Vr_ce0 <= Vr_ce0_local;
        end if; 
    end process;


    Vr_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Vr_ce0_local <= ap_const_logic_1;
        else 
            Vr_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    Vr_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Vr_we0_local <= ap_const_logic_1;
        else 
            Vr_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln76_fu_166_p2 <= std_logic_vector(unsigned(i_fu_54) + unsigned(ap_const_lv9_1));
    add_ln78_fu_176_p2 <= std_logic_vector(unsigned(zext_ln76_1_fu_172_p1) + unsigned(ap_const_lv16_9C41));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_on_subcall_done)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_on_subcall_done_assign_proc : process(grp_combineVOLEs_fu_142_ap_done, grp_combineVOLEs_fu_147_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((grp_combineVOLEs_fu_147_ap_done = ap_const_logic_0) or (grp_combineVOLEs_fu_142_ap_done = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln76_fu_160_p2)
    begin
        if ((icmp_ln76_fu_160_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(grp_combineVOLEs_fu_142_ap_return, ap_CS_fsm_state5, ap_return_0_preg, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_return_0 <= grp_combineVOLEs_fu_142_ap_return;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(grp_combineVOLEs_fu_147_ap_return, ap_CS_fsm_state5, ap_block_state5_on_subcall_done, ap_return_1_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_return_1 <= grp_combineVOLEs_fu_147_ap_return;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;

    grp_combineVOLEs_fu_142_ap_start <= grp_combineVOLEs_fu_142_ap_start_reg;
    grp_combineVOLEs_fu_147_ap_start <= grp_combineVOLEs_fu_147_ap_start_reg;
    icmp_ln76_fu_160_p2 <= "1" when (i_fu_54 = ap_const_lv9_110) else "0";
    lshr_ln_fu_182_p4 <= add_ln78_fu_176_p2(15 downto 1);
    select_ln78_fu_213_p3 <= 
        u_0_q0 when (trunc_ln76_fu_210_p1(0) = '1') else 
        u_1_q0;
    select_ln79_fu_226_p3 <= 
        V_0_q0 when (trunc_ln76_fu_210_p1(0) = '1') else 
        V_1_q0;
    trunc_ln76_fu_210_p1 <= i_13_reg_254(1 - 1 downto 0);
    u_0_address0 <= zext_ln78_1_fu_192_p1(18 - 1 downto 0);
    u_0_ce0 <= u_0_ce0_local;

    u_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            u_0_ce0_local <= ap_const_logic_1;
        else 
            u_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    u_1_address0 <= zext_ln78_1_fu_192_p1(18 - 1 downto 0);
    u_1_ce0 <= u_1_ce0_local;

    u_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            u_1_ce0_local <= ap_const_logic_1;
        else 
            u_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    ur_address0_assign_proc : process(grp_combineVOLEs_fu_142_vals_address0, ap_CS_fsm_state5, zext_ln76_fu_205_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ur_address0 <= grp_combineVOLEs_fu_142_vals_address0;
        else 
            ur_address0 <= zext_ln76_fu_205_p1(9 - 1 downto 0);
        end if; 
    end process;


    ur_ce0_assign_proc : process(grp_combineVOLEs_fu_142_vals_ce0, ap_CS_fsm_state5, ur_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ur_ce0 <= grp_combineVOLEs_fu_142_vals_ce0;
        else 
            ur_ce0 <= ur_ce0_local;
        end if; 
    end process;


    ur_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ur_ce0_local <= ap_const_logic_1;
        else 
            ur_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    ur_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ur_we0_local <= ap_const_logic_1;
        else 
            ur_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln76_1_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_54),16));
    zext_ln76_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_13_reg_254),64));
    zext_ln78_1_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_182_p4),64));
    zext_ln78_fu_221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln78_fu_213_p3),128));
end behav;
