// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_encrypt (
        ap_clk,
        ap_rst,
        in_r,
        key,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [127:0] in_r;
input  [127:0] key;
output  [127:0] ap_return;
input   ap_ce;

wire    ap_block_pp0_stage0_11001;
reg   [127:0] in_read_reg_120;
reg   [127:0] in_read_reg_120_pp0_iter1_reg;
reg   [127:0] in_read_reg_120_pp0_iter2_reg;
reg   [127:0] in_read_reg_120_pp0_iter3_reg;
reg   [127:0] in_read_reg_120_pp0_iter4_reg;
reg   [127:0] in_read_reg_120_pp0_iter5_reg;
reg   [127:0] in_read_reg_120_pp0_iter6_reg;
reg   [127:0] in_read_reg_120_pp0_iter7_reg;
reg   [127:0] in_read_reg_120_pp0_iter8_reg;
reg   [127:0] in_read_reg_120_pp0_iter9_reg;
reg   [127:0] in_read_reg_120_pp0_iter10_reg;
wire   [127:0] grp_updateKey_fu_34_ap_return_0;
wire   [127:0] grp_updateKey_fu_34_ap_return_1;
wire   [127:0] grp_updateKey_fu_34_ap_return_2;
wire   [127:0] grp_updateKey_fu_34_ap_return_3;
wire   [127:0] grp_updateKey_fu_34_ap_return_4;
wire   [127:0] grp_updateKey_fu_34_ap_return_5;
wire   [127:0] grp_updateKey_fu_34_ap_return_6;
wire   [127:0] grp_updateKey_fu_34_ap_return_7;
wire   [127:0] grp_updateKey_fu_34_ap_return_8;
wire   [127:0] grp_updateKey_fu_34_ap_return_9;
wire   [127:0] grp_updateKey_fu_34_ap_return_10;
reg    grp_updateKey_fu_34_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp26;
wire   [127:0] grp_process_r_fu_42_ap_return;
reg    grp_process_r_fu_42_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp49;
wire    ap_block_pp0_stage0_ignoreCallOp26;
wire    ap_block_pp0_stage0_ignoreCallOp49;
wire    ap_block_pp0_stage0;
reg   [127:0] in_r_int_reg;
reg   [127:0] key_int_reg;
wire    ap_ce_reg;

GenerateProof_updateKey grp_updateKey_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .cipherkey(key_int_reg),
    .ap_return_0(grp_updateKey_fu_34_ap_return_0),
    .ap_return_1(grp_updateKey_fu_34_ap_return_1),
    .ap_return_2(grp_updateKey_fu_34_ap_return_2),
    .ap_return_3(grp_updateKey_fu_34_ap_return_3),
    .ap_return_4(grp_updateKey_fu_34_ap_return_4),
    .ap_return_5(grp_updateKey_fu_34_ap_return_5),
    .ap_return_6(grp_updateKey_fu_34_ap_return_6),
    .ap_return_7(grp_updateKey_fu_34_ap_return_7),
    .ap_return_8(grp_updateKey_fu_34_ap_return_8),
    .ap_return_9(grp_updateKey_fu_34_ap_return_9),
    .ap_return_10(grp_updateKey_fu_34_ap_return_10),
    .ap_ce(grp_updateKey_fu_34_ap_ce)
);

GenerateProof_process_r grp_process_r_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .this_1_0_val(grp_updateKey_fu_34_ap_return_0),
    .this_1_1_val(grp_updateKey_fu_34_ap_return_1),
    .this_1_2_val(grp_updateKey_fu_34_ap_return_2),
    .this_1_3_val(grp_updateKey_fu_34_ap_return_3),
    .this_1_4_val(grp_updateKey_fu_34_ap_return_4),
    .this_1_5_val(grp_updateKey_fu_34_ap_return_5),
    .this_1_6_val(grp_updateKey_fu_34_ap_return_6),
    .this_1_7_val(grp_updateKey_fu_34_ap_return_7),
    .this_1_8_val(grp_updateKey_fu_34_ap_return_8),
    .this_1_9_val(grp_updateKey_fu_34_ap_return_9),
    .this_1_10_val(grp_updateKey_fu_34_ap_return_10),
    .plaintext(in_read_reg_120_pp0_iter10_reg),
    .ap_return(grp_process_r_fu_42_ap_return),
    .ap_ce(grp_process_r_fu_42_ap_ce)
);

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        in_r_int_reg <= in_r;
        key_int_reg <= key;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_read_reg_120 <= in_r_int_reg;
        in_read_reg_120_pp0_iter10_reg <= in_read_reg_120_pp0_iter9_reg;
        in_read_reg_120_pp0_iter1_reg <= in_read_reg_120;
        in_read_reg_120_pp0_iter2_reg <= in_read_reg_120_pp0_iter1_reg;
        in_read_reg_120_pp0_iter3_reg <= in_read_reg_120_pp0_iter2_reg;
        in_read_reg_120_pp0_iter4_reg <= in_read_reg_120_pp0_iter3_reg;
        in_read_reg_120_pp0_iter5_reg <= in_read_reg_120_pp0_iter4_reg;
        in_read_reg_120_pp0_iter6_reg <= in_read_reg_120_pp0_iter5_reg;
        in_read_reg_120_pp0_iter7_reg <= in_read_reg_120_pp0_iter6_reg;
        in_read_reg_120_pp0_iter8_reg <= in_read_reg_120_pp0_iter7_reg;
        in_read_reg_120_pp0_iter9_reg <= in_read_reg_120_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp49))) begin
        grp_process_r_fu_42_ap_ce = 1'b1;
    end else begin
        grp_process_r_fu_42_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp26))) begin
        grp_updateKey_fu_34_ap_ce = 1'b1;
    end else begin
        grp_updateKey_fu_34_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp26 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp49 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp26 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp49 = ~(1'b1 == 1'b1);

assign ap_return = grp_process_r_fu_42_ap_return;

endmodule //GenerateProof_encrypt
