// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_shakeXOF_32u_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        msgStrm_dout,
        msgStrm_empty_n,
        msgStrm_read,
        msgLenStrm_dout,
        msgLenStrm_empty_n,
        msgLenStrm_read,
        endMsgLenStrm_dout,
        endMsgLenStrm_empty_n,
        endMsgLenStrm_read,
        digestStrm_din,
        digestStrm_full_n,
        digestStrm_write,
        endDigestStrm_din,
        endDigestStrm_full_n,
        endDigestStrm_write
);

parameter    ap_ST_fsm_state1 = 138'd1;
parameter    ap_ST_fsm_state2 = 138'd2;
parameter    ap_ST_fsm_state3 = 138'd4;
parameter    ap_ST_fsm_state4 = 138'd8;
parameter    ap_ST_fsm_state5 = 138'd16;
parameter    ap_ST_fsm_state6 = 138'd32;
parameter    ap_ST_fsm_state7 = 138'd64;
parameter    ap_ST_fsm_state8 = 138'd128;
parameter    ap_ST_fsm_state9 = 138'd256;
parameter    ap_ST_fsm_state10 = 138'd512;
parameter    ap_ST_fsm_state11 = 138'd1024;
parameter    ap_ST_fsm_state12 = 138'd2048;
parameter    ap_ST_fsm_state13 = 138'd4096;
parameter    ap_ST_fsm_state14 = 138'd8192;
parameter    ap_ST_fsm_state15 = 138'd16384;
parameter    ap_ST_fsm_state16 = 138'd32768;
parameter    ap_ST_fsm_state17 = 138'd65536;
parameter    ap_ST_fsm_state18 = 138'd131072;
parameter    ap_ST_fsm_state19 = 138'd262144;
parameter    ap_ST_fsm_state20 = 138'd524288;
parameter    ap_ST_fsm_state21 = 138'd1048576;
parameter    ap_ST_fsm_state22 = 138'd2097152;
parameter    ap_ST_fsm_state23 = 138'd4194304;
parameter    ap_ST_fsm_state24 = 138'd8388608;
parameter    ap_ST_fsm_state25 = 138'd16777216;
parameter    ap_ST_fsm_state26 = 138'd33554432;
parameter    ap_ST_fsm_state27 = 138'd67108864;
parameter    ap_ST_fsm_state28 = 138'd134217728;
parameter    ap_ST_fsm_state29 = 138'd268435456;
parameter    ap_ST_fsm_state30 = 138'd536870912;
parameter    ap_ST_fsm_state31 = 138'd1073741824;
parameter    ap_ST_fsm_state32 = 138'd2147483648;
parameter    ap_ST_fsm_state33 = 138'd4294967296;
parameter    ap_ST_fsm_state34 = 138'd8589934592;
parameter    ap_ST_fsm_state35 = 138'd17179869184;
parameter    ap_ST_fsm_state36 = 138'd34359738368;
parameter    ap_ST_fsm_state37 = 138'd68719476736;
parameter    ap_ST_fsm_state38 = 138'd137438953472;
parameter    ap_ST_fsm_state39 = 138'd274877906944;
parameter    ap_ST_fsm_state40 = 138'd549755813888;
parameter    ap_ST_fsm_state41 = 138'd1099511627776;
parameter    ap_ST_fsm_state42 = 138'd2199023255552;
parameter    ap_ST_fsm_state43 = 138'd4398046511104;
parameter    ap_ST_fsm_state44 = 138'd8796093022208;
parameter    ap_ST_fsm_state45 = 138'd17592186044416;
parameter    ap_ST_fsm_state46 = 138'd35184372088832;
parameter    ap_ST_fsm_state47 = 138'd70368744177664;
parameter    ap_ST_fsm_state48 = 138'd140737488355328;
parameter    ap_ST_fsm_state49 = 138'd281474976710656;
parameter    ap_ST_fsm_state50 = 138'd562949953421312;
parameter    ap_ST_fsm_state51 = 138'd1125899906842624;
parameter    ap_ST_fsm_state52 = 138'd2251799813685248;
parameter    ap_ST_fsm_state53 = 138'd4503599627370496;
parameter    ap_ST_fsm_state54 = 138'd9007199254740992;
parameter    ap_ST_fsm_state55 = 138'd18014398509481984;
parameter    ap_ST_fsm_state56 = 138'd36028797018963968;
parameter    ap_ST_fsm_state57 = 138'd72057594037927936;
parameter    ap_ST_fsm_state58 = 138'd144115188075855872;
parameter    ap_ST_fsm_state59 = 138'd288230376151711744;
parameter    ap_ST_fsm_state60 = 138'd576460752303423488;
parameter    ap_ST_fsm_state61 = 138'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 138'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 138'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 138'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 138'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 138'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 138'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 138'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 138'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 138'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 138'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 138'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 138'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 138'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 138'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 138'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 138'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 138'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 138'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 138'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 138'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 138'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 138'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 138'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 138'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 138'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 138'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 138'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 138'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 138'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 138'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 138'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 138'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 138'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 138'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 138'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 138'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 138'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 138'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 138'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 138'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 138'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 138'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 138'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 138'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 138'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 138'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 138'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 138'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 138'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 138'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 138'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 138'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 138'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 138'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 138'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 138'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 138'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 138'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 138'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 138'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 138'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 138'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 138'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 138'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 138'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 138'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 138'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 138'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 138'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 138'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 138'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 138'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 138'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 138'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 138'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 138'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 138'd174224571863520493293247799005065324265472;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] msgStrm_dout;
input   msgStrm_empty_n;
output   msgStrm_read;
input  [127:0] msgLenStrm_dout;
input   msgLenStrm_empty_n;
output   msgLenStrm_read;
input  [0:0] endMsgLenStrm_dout;
input   endMsgLenStrm_empty_n;
output   endMsgLenStrm_read;
output  [255:0] digestStrm_din;
input   digestStrm_full_n;
output   digestStrm_write;
output  [0:0] endDigestStrm_din;
input   endDigestStrm_full_n;
output   endDigestStrm_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg msgStrm_read;
reg msgLenStrm_read;
reg endMsgLenStrm_read;
reg digestStrm_write;
reg[0:0] endDigestStrm_din;
reg endDigestStrm_write;

(* fsm_encoding = "none" *) reg   [137:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    msgLenStrm_blk_n;
wire    ap_CS_fsm_state2;
reg    endMsgLenStrm_blk_n;
wire    ap_CS_fsm_state134;
wire   [0:0] icmp_ln447_fu_520_p2;
reg    digestStrm_blk_n;
reg    endDigestStrm_blk_n;
reg   [127:0] msgLen_reg_967;
wire   [120:0] add_ln447_fu_514_p2;
reg   [120:0] add_ln447_reg_973;
wire    ap_CS_fsm_state133;
wire   [120:0] n_2_fu_525_p2;
reg   [120:0] n_2_reg_981;
reg    ap_block_state134;
reg   [4:0] trunc_ln3_cast_reg_986;
wire   [2:0] empty_fu_548_p1;
reg   [2:0] empty_reg_994;
wire   [127:0] left_5_fu_566_p2;
wire    ap_CS_fsm_state136;
reg   [63:0] stateArray_load_1_reg_1009;
wire    ap_CS_fsm_state137;
reg   [63:0] stateArray_1_load_1_reg_1014;
reg   [63:0] stateArray_2_load_1_reg_1019;
reg   [63:0] stateArray_3_load_1_reg_1024;
wire    ap_CS_fsm_state138;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_done;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_idle;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_ready;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_msgStrm_read;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_1_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_1_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_2_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_2_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_3_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_3_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_4_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_4_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_5_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_5_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_6_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_6_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_7_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_7_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_8_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_8_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_9_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_9_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_10_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_10_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_11_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_11_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_12_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_12_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_13_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_13_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_14_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_14_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_15_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_15_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_16_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_16_o_ap_vld;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_done;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_idle;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_ready;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_msgStrm_read;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_16_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_16_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_15_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_15_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_14_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_14_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_13_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_13_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_12_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_12_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_11_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_11_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_10_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_10_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_9_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_9_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_8_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_8_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_7_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_7_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_6_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_6_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_5_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_5_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_4_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_4_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_3_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_3_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_2_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_2_o_ap_vld;
wire   [63:0] grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_1_o;
wire    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_1_o_ap_vld;
wire    grp_KECCAK_f_fu_364_ap_start;
wire    grp_KECCAK_f_fu_364_ap_done;
wire    grp_KECCAK_f_fu_364_ap_idle;
wire    grp_KECCAK_f_fu_364_ap_ready;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_0;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_1;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_2;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_3;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_4;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_5;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_6;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_7;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_8;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_9;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_10;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_11;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_12;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_13;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_14;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_15;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_16;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_17;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_18;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_19;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_20;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_21;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_22;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_23;
wire   [63:0] grp_KECCAK_f_fu_364_ap_return_24;
reg   [0:0] endFlag_1_reg_178;
reg    ap_block_state1;
reg   [63:0] stateArray_20_0_reg_187;
reg   [63:0] stateArray_19_0_reg_199;
reg   [63:0] stateArray_18_0_reg_211;
reg   [63:0] stateArray_17_0_reg_223;
reg   [63:0] stateArray_21_0_reg_235;
reg   [63:0] stateArray_22_0_reg_247;
reg   [63:0] stateArray_23_0_reg_259;
reg   [63:0] stateArray_24_0_reg_271;
reg   [120:0] n_reg_283;
reg   [127:0] left_4_reg_294;
reg   [127:0] left_1_reg_304;
wire    ap_CS_fsm_state135;
reg    grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start_reg;
reg    ap_block_state134_ignore_call1;
wire   [0:0] icmp_ln450_fu_542_p2;
reg   [63:0] stateArray_fu_82;
reg   [63:0] stateArray_1_fu_86;
reg   [63:0] stateArray_2_fu_90;
reg   [63:0] stateArray_3_fu_94;
reg   [63:0] stateArray_4_fu_98;
reg   [63:0] stateArray_5_fu_102;
reg   [63:0] stateArray_6_fu_106;
reg   [63:0] stateArray_7_fu_110;
reg   [63:0] stateArray_8_fu_114;
reg   [63:0] stateArray_9_fu_118;
reg   [63:0] stateArray_10_fu_122;
reg   [63:0] stateArray_11_fu_126;
reg   [63:0] stateArray_12_fu_130;
reg   [63:0] stateArray_13_fu_134;
reg   [63:0] stateArray_14_fu_138;
reg   [63:0] stateArray_15_fu_142;
reg   [63:0] stateArray_16_fu_146;
reg    grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start_reg;
reg    ap_block_state134_ignore_call0;
reg    grp_KECCAK_f_fu_364_ap_start_reg;
reg    ap_block_state2;
wire   [8:0] grp_fu_419_p1;
wire   [127:0] grp_fu_419_p2;
wire   [120:0] trunc_ln427_fu_510_p1;
reg    grp_fu_419_ce;
reg   [137:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
wire    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
wire    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
wire    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
wire    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
wire    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
wire    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ST_fsm_state131_blk;
wire    ap_ST_fsm_state132_blk;
wire    ap_ST_fsm_state133_blk;
reg    ap_ST_fsm_state134_blk;
reg    ap_ST_fsm_state135_blk;
reg    ap_ST_fsm_state136_blk;
wire    ap_ST_fsm_state137_blk;
reg    ap_ST_fsm_state138_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 138'd1;
#0 grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start_reg = 1'b0;
#0 stateArray_fu_82 = 64'd0;
#0 stateArray_1_fu_86 = 64'd0;
#0 stateArray_2_fu_90 = 64'd0;
#0 stateArray_3_fu_94 = 64'd0;
#0 stateArray_4_fu_98 = 64'd0;
#0 stateArray_5_fu_102 = 64'd0;
#0 stateArray_6_fu_106 = 64'd0;
#0 stateArray_7_fu_110 = 64'd0;
#0 stateArray_8_fu_114 = 64'd0;
#0 stateArray_9_fu_118 = 64'd0;
#0 stateArray_10_fu_122 = 64'd0;
#0 stateArray_11_fu_126 = 64'd0;
#0 stateArray_12_fu_130 = 64'd0;
#0 stateArray_13_fu_134 = 64'd0;
#0 stateArray_14_fu_138 = 64'd0;
#0 stateArray_15_fu_142 = 64'd0;
#0 stateArray_16_fu_146 = 64'd0;
#0 grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start_reg = 1'b0;
#0 grp_KECCAK_f_fu_364_ap_start_reg = 1'b0;
end

GenerateProof_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start),
    .ap_done(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_done),
    .ap_idle(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_idle),
    .ap_ready(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_ready),
    .msgStrm_dout(msgStrm_dout),
    .msgStrm_empty_n(msgStrm_empty_n),
    .msgStrm_read(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_msgStrm_read),
    .stateArray_i(stateArray_fu_82),
    .stateArray_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_o),
    .stateArray_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_o_ap_vld),
    .stateArray_1_i(stateArray_1_fu_86),
    .stateArray_1_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_1_o),
    .stateArray_1_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_1_o_ap_vld),
    .stateArray_2_i(stateArray_2_fu_90),
    .stateArray_2_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_2_o),
    .stateArray_2_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_2_o_ap_vld),
    .stateArray_3_i(stateArray_3_fu_94),
    .stateArray_3_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_3_o),
    .stateArray_3_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_3_o_ap_vld),
    .stateArray_4_i(stateArray_4_fu_98),
    .stateArray_4_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_4_o),
    .stateArray_4_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_4_o_ap_vld),
    .stateArray_5_i(stateArray_5_fu_102),
    .stateArray_5_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_5_o),
    .stateArray_5_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_5_o_ap_vld),
    .stateArray_6_i(stateArray_6_fu_106),
    .stateArray_6_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_6_o),
    .stateArray_6_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_6_o_ap_vld),
    .stateArray_7_i(stateArray_7_fu_110),
    .stateArray_7_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_7_o),
    .stateArray_7_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_7_o_ap_vld),
    .stateArray_8_i(stateArray_8_fu_114),
    .stateArray_8_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_8_o),
    .stateArray_8_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_8_o_ap_vld),
    .stateArray_9_i(stateArray_9_fu_118),
    .stateArray_9_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_9_o),
    .stateArray_9_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_9_o_ap_vld),
    .stateArray_10_i(stateArray_10_fu_122),
    .stateArray_10_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_10_o),
    .stateArray_10_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_10_o_ap_vld),
    .stateArray_11_i(stateArray_11_fu_126),
    .stateArray_11_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_11_o),
    .stateArray_11_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_11_o_ap_vld),
    .stateArray_12_i(stateArray_12_fu_130),
    .stateArray_12_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_12_o),
    .stateArray_12_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_12_o_ap_vld),
    .stateArray_13_i(stateArray_13_fu_134),
    .stateArray_13_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_13_o),
    .stateArray_13_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_13_o_ap_vld),
    .stateArray_14_i(stateArray_14_fu_138),
    .stateArray_14_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_14_o),
    .stateArray_14_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_14_o_ap_vld),
    .stateArray_15_i(stateArray_15_fu_142),
    .stateArray_15_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_15_o),
    .stateArray_15_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_15_o_ap_vld),
    .stateArray_16_i(stateArray_16_fu_146),
    .stateArray_16_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_16_o),
    .stateArray_16_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_16_o_ap_vld),
    .trunc_ln3(trunc_ln3_cast_reg_986),
    .empty(empty_reg_994)
);

GenerateProof_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start),
    .ap_done(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_done),
    .ap_idle(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_idle),
    .ap_ready(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_ready),
    .msgStrm_dout(msgStrm_dout),
    .msgStrm_empty_n(msgStrm_empty_n),
    .msgStrm_read(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_msgStrm_read),
    .stateArray_i(stateArray_fu_82),
    .stateArray_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_o),
    .stateArray_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_o_ap_vld),
    .stateArray_16_i(stateArray_16_fu_146),
    .stateArray_16_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_16_o),
    .stateArray_16_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_16_o_ap_vld),
    .stateArray_15_i(stateArray_15_fu_142),
    .stateArray_15_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_15_o),
    .stateArray_15_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_15_o_ap_vld),
    .stateArray_14_i(stateArray_14_fu_138),
    .stateArray_14_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_14_o),
    .stateArray_14_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_14_o_ap_vld),
    .stateArray_13_i(stateArray_13_fu_134),
    .stateArray_13_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_13_o),
    .stateArray_13_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_13_o_ap_vld),
    .stateArray_12_i(stateArray_12_fu_130),
    .stateArray_12_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_12_o),
    .stateArray_12_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_12_o_ap_vld),
    .stateArray_11_i(stateArray_11_fu_126),
    .stateArray_11_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_11_o),
    .stateArray_11_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_11_o_ap_vld),
    .stateArray_10_i(stateArray_10_fu_122),
    .stateArray_10_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_10_o),
    .stateArray_10_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_10_o_ap_vld),
    .stateArray_9_i(stateArray_9_fu_118),
    .stateArray_9_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_9_o),
    .stateArray_9_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_9_o_ap_vld),
    .stateArray_8_i(stateArray_8_fu_114),
    .stateArray_8_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_8_o),
    .stateArray_8_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_8_o_ap_vld),
    .stateArray_7_i(stateArray_7_fu_110),
    .stateArray_7_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_7_o),
    .stateArray_7_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_7_o_ap_vld),
    .stateArray_6_i(stateArray_6_fu_106),
    .stateArray_6_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_6_o),
    .stateArray_6_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_6_o_ap_vld),
    .stateArray_5_i(stateArray_5_fu_102),
    .stateArray_5_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_5_o),
    .stateArray_5_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_5_o_ap_vld),
    .stateArray_4_i(stateArray_4_fu_98),
    .stateArray_4_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_4_o),
    .stateArray_4_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_4_o_ap_vld),
    .stateArray_3_i(stateArray_3_fu_94),
    .stateArray_3_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_3_o),
    .stateArray_3_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_3_o_ap_vld),
    .stateArray_2_i(stateArray_2_fu_90),
    .stateArray_2_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_2_o),
    .stateArray_2_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_2_o_ap_vld),
    .stateArray_1_i(stateArray_1_fu_86),
    .stateArray_1_o(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_1_o),
    .stateArray_1_o_ap_vld(grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_1_o_ap_vld)
);

GenerateProof_KECCAK_f grp_KECCAK_f_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_KECCAK_f_fu_364_ap_start),
    .ap_done(grp_KECCAK_f_fu_364_ap_done),
    .ap_idle(grp_KECCAK_f_fu_364_ap_idle),
    .ap_ready(grp_KECCAK_f_fu_364_ap_ready),
    .stateArray_0_read(stateArray_load_1_reg_1009),
    .stateArray_1_read(stateArray_1_load_1_reg_1014),
    .stateArray_2_read(stateArray_2_load_1_reg_1019),
    .stateArray_3_read(stateArray_3_load_1_reg_1024),
    .stateArray_4_read(stateArray_4_fu_98),
    .stateArray_5_read(stateArray_5_fu_102),
    .stateArray_6_read(stateArray_6_fu_106),
    .stateArray_7_read(stateArray_7_fu_110),
    .stateArray_8_read(stateArray_8_fu_114),
    .stateArray_9_read(stateArray_9_fu_118),
    .stateArray_10_read(stateArray_10_fu_122),
    .stateArray_11_read(stateArray_11_fu_126),
    .stateArray_1213_read(stateArray_12_fu_130),
    .stateArray_13_read(stateArray_13_fu_134),
    .stateArray_14_read(stateArray_14_fu_138),
    .stateArray_15_read(stateArray_15_fu_142),
    .stateArray_16_read(stateArray_16_fu_146),
    .stateArray_17_read(stateArray_17_0_reg_223),
    .stateArray_18_read(stateArray_18_0_reg_211),
    .stateArray_19_read(stateArray_19_0_reg_199),
    .stateArray_20_read(stateArray_20_0_reg_187),
    .stateArray_21_read(stateArray_21_0_reg_235),
    .stateArray_22_read(stateArray_22_0_reg_247),
    .stateArray_2325_read(stateArray_23_0_reg_259),
    .stateArray_24_read(stateArray_24_0_reg_271),
    .ap_return_0(grp_KECCAK_f_fu_364_ap_return_0),
    .ap_return_1(grp_KECCAK_f_fu_364_ap_return_1),
    .ap_return_2(grp_KECCAK_f_fu_364_ap_return_2),
    .ap_return_3(grp_KECCAK_f_fu_364_ap_return_3),
    .ap_return_4(grp_KECCAK_f_fu_364_ap_return_4),
    .ap_return_5(grp_KECCAK_f_fu_364_ap_return_5),
    .ap_return_6(grp_KECCAK_f_fu_364_ap_return_6),
    .ap_return_7(grp_KECCAK_f_fu_364_ap_return_7),
    .ap_return_8(grp_KECCAK_f_fu_364_ap_return_8),
    .ap_return_9(grp_KECCAK_f_fu_364_ap_return_9),
    .ap_return_10(grp_KECCAK_f_fu_364_ap_return_10),
    .ap_return_11(grp_KECCAK_f_fu_364_ap_return_11),
    .ap_return_12(grp_KECCAK_f_fu_364_ap_return_12),
    .ap_return_13(grp_KECCAK_f_fu_364_ap_return_13),
    .ap_return_14(grp_KECCAK_f_fu_364_ap_return_14),
    .ap_return_15(grp_KECCAK_f_fu_364_ap_return_15),
    .ap_return_16(grp_KECCAK_f_fu_364_ap_return_16),
    .ap_return_17(grp_KECCAK_f_fu_364_ap_return_17),
    .ap_return_18(grp_KECCAK_f_fu_364_ap_return_18),
    .ap_return_19(grp_KECCAK_f_fu_364_ap_return_19),
    .ap_return_20(grp_KECCAK_f_fu_364_ap_return_20),
    .ap_return_21(grp_KECCAK_f_fu_364_ap_return_21),
    .ap_return_22(grp_KECCAK_f_fu_364_ap_return_22),
    .ap_return_23(grp_KECCAK_f_fu_364_ap_return_23),
    .ap_return_24(grp_KECCAK_f_fu_364_ap_return_24)
);

GenerateProof_udiv_128ns_9ns_128_132_1 #(
    .ID( 1 ),
    .NUM_STAGE( 132 ),
    .din0_WIDTH( 128 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 128 ))
udiv_128ns_9ns_128_132_1_U122(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(msgLenStrm_dout),
    .din1(grp_fu_419_p1),
    .ce(grp_fu_419_ce),
    .dout(grp_fu_419_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_KECCAK_f_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state137)) begin
            grp_KECCAK_f_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_KECCAK_f_fu_364_ap_ready == 1'b1)) begin
            grp_KECCAK_f_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln450_fu_542_p2 == 1'd1) & (1'b0 == ap_block_state134_ignore_call0) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd0))) begin
            grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start_reg <= 1'b1;
        end else if ((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_ready == 1'b1)) begin
            grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln450_fu_542_p2 == 1'd0) & (1'b0 == ap_block_state134_ignore_call1) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd0))) begin
            grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start_reg <= 1'b1;
        end else if ((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_ready == 1'b1)) begin
            grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        left_1_reg_304 <= left_4_reg_294;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        left_1_reg_304 <= left_5_fu_566_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        left_4_reg_294 <= left_1_reg_304;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        left_4_reg_294 <= msgLen_reg_967;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        n_reg_283 <= n_2_reg_981;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        n_reg_283 <= 121'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_10_fu_122 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_10_fu_122 <= grp_KECCAK_f_fu_364_ap_return_10;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_10_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_10_fu_122 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_10_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_10_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_10_fu_122 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_10_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_11_fu_126 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_11_fu_126 <= grp_KECCAK_f_fu_364_ap_return_11;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_11_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_11_fu_126 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_11_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_11_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_11_fu_126 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_12_fu_130 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_12_fu_130 <= grp_KECCAK_f_fu_364_ap_return_12;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_12_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_12_fu_130 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_12_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_12_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_12_fu_130 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_13_fu_134 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_13_fu_134 <= grp_KECCAK_f_fu_364_ap_return_13;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_13_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_13_fu_134 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_13_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_13_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_13_fu_134 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_14_fu_138 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_14_fu_138 <= grp_KECCAK_f_fu_364_ap_return_14;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_14_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_14_fu_138 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_14_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_14_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_14_fu_138 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_15_fu_142 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_15_fu_142 <= grp_KECCAK_f_fu_364_ap_return_15;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_15_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_15_fu_142 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_15_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_15_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_15_fu_142 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_15_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_16_fu_146 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_16_fu_146 <= grp_KECCAK_f_fu_364_ap_return_16;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_16_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_16_fu_146 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_16_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_16_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_16_fu_146 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_16_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_17_0_reg_223 <= grp_KECCAK_f_fu_364_ap_return_17;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_17_0_reg_223 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_18_0_reg_211 <= grp_KECCAK_f_fu_364_ap_return_18;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_18_0_reg_211 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_19_0_reg_199 <= grp_KECCAK_f_fu_364_ap_return_19;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_19_0_reg_199 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_1_fu_86 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_1_fu_86 <= grp_KECCAK_f_fu_364_ap_return_1;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_1_fu_86 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_1_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_1_fu_86 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_20_0_reg_187 <= grp_KECCAK_f_fu_364_ap_return_20;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_20_0_reg_187 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_21_0_reg_235 <= grp_KECCAK_f_fu_364_ap_return_21;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_21_0_reg_235 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_22_0_reg_247 <= grp_KECCAK_f_fu_364_ap_return_22;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_22_0_reg_247 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_23_0_reg_259 <= grp_KECCAK_f_fu_364_ap_return_23;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_23_0_reg_259 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_24_0_reg_271 <= grp_KECCAK_f_fu_364_ap_return_24;
    end else if ((1'b1 == ap_CS_fsm_state133)) begin
        stateArray_24_0_reg_271 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_2_fu_90 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_2_fu_90 <= grp_KECCAK_f_fu_364_ap_return_2;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_2_fu_90 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_2_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_2_fu_90 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_3_fu_94 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_3_fu_94 <= grp_KECCAK_f_fu_364_ap_return_3;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_3_fu_94 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_3_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_3_fu_94 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_4_fu_98 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_4_fu_98 <= grp_KECCAK_f_fu_364_ap_return_4;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_4_fu_98 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_4_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_4_fu_98 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_5_fu_102 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_5_fu_102 <= grp_KECCAK_f_fu_364_ap_return_5;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_5_fu_102 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_5_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_5_fu_102 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_6_fu_106 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_6_fu_106 <= grp_KECCAK_f_fu_364_ap_return_6;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_6_fu_106 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_6_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_6_fu_106 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_7_fu_110 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_7_fu_110 <= grp_KECCAK_f_fu_364_ap_return_7;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_7_fu_110 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_7_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_7_fu_110 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_8_fu_114 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_8_fu_114 <= grp_KECCAK_f_fu_364_ap_return_8;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_8_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_8_fu_114 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_8_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_8_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_8_fu_114 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_8_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_9_fu_118 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_9_fu_118 <= grp_KECCAK_f_fu_364_ap_return_9;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_9_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_9_fu_118 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_9_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_9_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_9_fu_118 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_9_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        stateArray_fu_82 <= 64'd0;
    end else if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
        stateArray_fu_82 <= grp_KECCAK_f_fu_364_ap_return_0;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
        stateArray_fu_82 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_stateArray_o;
    end else if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
        stateArray_fu_82 <= grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_stateArray_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state133)) begin
        add_ln447_reg_973 <= add_ln447_fu_514_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state134)) begin
        empty_reg_994 <= empty_fu_548_p1;
        trunc_ln3_cast_reg_986 <= {{left_4_reg_294[7:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1)))) begin
        endFlag_1_reg_178 <= endMsgLenStrm_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        msgLen_reg_967 <= msgLenStrm_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134))) begin
        n_2_reg_981 <= n_2_fu_525_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state137)) begin
        stateArray_1_load_1_reg_1014 <= stateArray_1_fu_86;
        stateArray_2_load_1_reg_1019 <= stateArray_2_fu_90;
        stateArray_3_load_1_reg_1024 <= stateArray_3_fu_94;
        stateArray_load_1_reg_1009 <= stateArray_fu_82;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

assign ap_ST_fsm_state117_blk = 1'b0;

assign ap_ST_fsm_state118_blk = 1'b0;

assign ap_ST_fsm_state119_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

assign ap_ST_fsm_state121_blk = 1'b0;

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

assign ap_ST_fsm_state125_blk = 1'b0;

assign ap_ST_fsm_state126_blk = 1'b0;

assign ap_ST_fsm_state127_blk = 1'b0;

assign ap_ST_fsm_state128_blk = 1'b0;

assign ap_ST_fsm_state129_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state131_blk = 1'b0;

assign ap_ST_fsm_state132_blk = 1'b0;

assign ap_ST_fsm_state133_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state134)) begin
        ap_ST_fsm_state134_blk = 1'b1;
    end else begin
        ap_ST_fsm_state134_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_done == 1'b0)) begin
        ap_ST_fsm_state135_blk = 1'b1;
    end else begin
        ap_ST_fsm_state135_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_done == 1'b0)) begin
        ap_ST_fsm_state136_blk = 1'b1;
    end else begin
        ap_ST_fsm_state136_blk = 1'b0;
    end
end

assign ap_ST_fsm_state137_blk = 1'b0;

always @ (*) begin
    if ((grp_KECCAK_f_fu_364_ap_done == 1'b0)) begin
        ap_ST_fsm_state138_blk = 1'b1;
    end else begin
        ap_ST_fsm_state138_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1))) begin
        digestStrm_blk_n = digestStrm_full_n;
    end else begin
        digestStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1))) begin
        digestStrm_write = 1'b1;
    end else begin
        digestStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd1)))) begin
        endDigestStrm_blk_n = endDigestStrm_full_n;
    end else begin
        endDigestStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1))) begin
        endDigestStrm_din = 1'd0;
    end else if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd1))) begin
        endDigestStrm_din = 1'd1;
    end else begin
        endDigestStrm_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd1)) | ((1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1)))) begin
        endDigestStrm_write = 1'b1;
    end else begin
        endDigestStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        endMsgLenStrm_blk_n = endMsgLenStrm_empty_n;
    end else begin
        endMsgLenStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1)))) begin
        endMsgLenStrm_read = 1'b1;
    end else begin
        endMsgLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state135) | (1'b1 == ap_CS_fsm_state138) | (1'b1 == ap_CS_fsm_state137) | (1'b1 == ap_CS_fsm_state136) | (1'b1 == ap_CS_fsm_state134) | (1'b1 == ap_CS_fsm_state1) | ((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_block_state2)))) begin
        grp_fu_419_ce = 1'b0;
    end else begin
        grp_fu_419_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        msgLenStrm_blk_n = msgLenStrm_empty_n;
    end else begin
        msgLenStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
        msgLenStrm_read = 1'b1;
    end else begin
        msgLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state136)) begin
        msgStrm_read = grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_msgStrm_read;
    end else if ((1'b1 == ap_CS_fsm_state135)) begin
        msgStrm_read = grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_msgStrm_read;
    end else begin
        msgStrm_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2) & (endFlag_1_reg_178 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            if (((1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln450_fu_542_p2 == 1'd1) & (1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state136;
            end else if (((icmp_ln450_fu_542_p2 == 1'd0) & (1'b0 == ap_block_state134) & (1'b1 == ap_CS_fsm_state134) & (icmp_ln447_fu_520_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state135;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state134;
            end
        end
        ap_ST_fsm_state135 : begin
            if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state135))) begin
                ap_NS_fsm = ap_ST_fsm_state137;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state135;
            end
        end
        ap_ST_fsm_state136 : begin
            if (((grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state136))) begin
                ap_NS_fsm = ap_ST_fsm_state137;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state136;
            end
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            if (((grp_KECCAK_f_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state138))) begin
                ap_NS_fsm = ap_ST_fsm_state134;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state138;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln447_fu_514_p2 = (trunc_ln427_fu_510_p1 + 121'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state133 = ap_CS_fsm[32'd132];

assign ap_CS_fsm_state134 = ap_CS_fsm[32'd133];

assign ap_CS_fsm_state135 = ap_CS_fsm[32'd134];

assign ap_CS_fsm_state136 = ap_CS_fsm[32'd135];

assign ap_CS_fsm_state137 = ap_CS_fsm[32'd136];

assign ap_CS_fsm_state138 = ap_CS_fsm[32'd137];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((endMsgLenStrm_empty_n == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state134 = (((icmp_ln447_fu_520_p2 == 1'd1) & (endMsgLenStrm_empty_n == 1'b0)) | ((icmp_ln447_fu_520_p2 == 1'd1) & (endDigestStrm_full_n == 1'b0)) | ((icmp_ln447_fu_520_p2 == 1'd1) & (digestStrm_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state134_ignore_call0 = (((icmp_ln447_fu_520_p2 == 1'd1) & (endMsgLenStrm_empty_n == 1'b0)) | ((icmp_ln447_fu_520_p2 == 1'd1) & (endDigestStrm_full_n == 1'b0)) | ((icmp_ln447_fu_520_p2 == 1'd1) & (digestStrm_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state134_ignore_call1 = (((icmp_ln447_fu_520_p2 == 1'd1) & (endMsgLenStrm_empty_n == 1'b0)) | ((icmp_ln447_fu_520_p2 == 1'd1) & (endDigestStrm_full_n == 1'b0)) | ((icmp_ln447_fu_520_p2 == 1'd1) & (digestStrm_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2 = (((endFlag_1_reg_178 == 1'd1) & (endDigestStrm_full_n == 1'b0)) | ((endFlag_1_reg_178 == 1'd0) & (msgLenStrm_empty_n == 1'b0)));
end

assign digestStrm_din = {{{{stateArray_3_fu_94}, {stateArray_2_fu_90}}, {stateArray_1_fu_86}}, {stateArray_fu_82}};

assign empty_fu_548_p1 = left_4_reg_294[2:0];

assign grp_KECCAK_f_fu_364_ap_start = grp_KECCAK_f_fu_364_ap_start_reg;

assign grp_fu_419_p1 = 128'd136;

assign grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start = grp_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK_fu_341_ap_start_reg;

assign grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start = grp_shakeXOF_32u_Pipeline_LOOP_GEN_LAST_BLK_fu_316_ap_start_reg;

assign icmp_ln447_fu_520_p2 = ((n_reg_283 == add_ln447_reg_973) ? 1'b1 : 1'b0);

assign icmp_ln450_fu_542_p2 = ((left_4_reg_294 > 128'd135) ? 1'b1 : 1'b0);

assign left_5_fu_566_p2 = ($signed(left_4_reg_294) + $signed(128'd340282366920938463463374607431768211320));

assign n_2_fu_525_p2 = (n_reg_283 + 121'd1);

assign trunc_ln427_fu_510_p1 = grp_fu_419_p2[120:0];

endmodule //GenerateProof_shakeXOF_32u_s
