// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_chal2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        d_strm_cp_dout,
        d_strm_cp_empty_n,
        d_strm_cp_read,
        d_strm_cp_num_data_valid,
        d_strm_cp_fifo_cap,
        ch1_val,
        ch2_strm_din,
        ch2_strm_full_n,
        ch2_strm_write,
        ch2_strm_num_data_valid,
        ch2_strm_fifo_cap
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_pp0_stage0 = 7'd2;
parameter    ap_ST_fsm_state5 = 7'd4;
parameter    ap_ST_fsm_state6 = 7'd8;
parameter    ap_ST_fsm_state7 = 7'd16;
parameter    ap_ST_fsm_state8 = 7'd32;
parameter    ap_ST_fsm_state9 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] d_strm_cp_dout;
input   d_strm_cp_empty_n;
output   d_strm_cp_read;
input  [2:0] d_strm_cp_num_data_valid;
input  [2:0] d_strm_cp_fifo_cap;
input  [127:0] ch1_val;
output  [127:0] ch2_strm_din;
input   ch2_strm_full_n;
output   ch2_strm_write;
input  [2:0] ch2_strm_num_data_valid;
input  [2:0] ch2_strm_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg d_strm_cp_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    d_strm_cp_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [63:0] msgStrm_din;
wire    msgStrm_full_n;
reg    msgStrm_write;
wire    ap_block_pp0_stage0_grp1;
reg   [0:0] icmp_ln73_reg_462;
reg   [127:0] ch1_val_read_reg_407;
reg    ap_block_state1;
wire   [0:0] icmp_ln70_fu_250_p2;
reg   [0:0] icmp_ln70_reg_452;
reg    ap_block_state3_pp0_stage0_iter1_grp1;
reg   [0:0] icmp_ln70_1_reg_466;
reg   [0:0] icmp_ln70_1_reg_466_pp0_iter1_reg;
reg    ap_block_state4_pp0_stage0_iter2_grp1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] trunc_ln70_fu_290_p1;
reg   [5:0] trunc_ln70_reg_457;
wire   [0:0] icmp_ln73_fu_300_p2;
wire   [0:0] icmp_ln70_1_fu_312_p2;
reg   [63:0] p_0_reg_470;
wire    ap_CS_fsm_state5;
wire    msgLenStrm_full_n;
reg    msgLenStrm_write;
wire    outLenStrm_full_n;
reg    outLenStrm_write;
reg   [0:0] endMsgLenStrm_din;
wire    endMsgLenStrm_full_n;
reg    endMsgLenStrm_write;
reg   [0:0] endOutLenStrm_din;
wire    endOutLenStrm_full_n;
reg    endOutLenStrm_write;
reg    ap_block_state5;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln67_fu_232_p2;
reg    ap_condition_pp0_exit_iter0_state2;
wire    grp_shake_extensible_fu_195_ap_start;
wire    grp_shake_extensible_fu_195_ap_done;
wire    grp_shake_extensible_fu_195_ap_idle;
wire    grp_shake_extensible_fu_195_ap_ready;
wire    grp_shake_extensible_fu_195_msgStrm_read;
wire    grp_shake_extensible_fu_195_msgLenStrm_read;
wire    grp_shake_extensible_fu_195_endMsgLenStrm_read;
wire    grp_shake_extensible_fu_195_outLenStrm_read;
wire    grp_shake_extensible_fu_195_endOutLenStrm_read;
wire   [127:0] grp_shake_extensible_fu_195_ch2_strm_din;
wire    grp_shake_extensible_fu_195_ch2_strm_write;
wire   [0:0] grp_shake_extensible_fu_195_endDigestStrm_internal_din;
wire    grp_shake_extensible_fu_195_endDigestStrm_internal_write;
reg    grp_shake_extensible_fu_195_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [63:0] msgStrm_dout;
wire    msgStrm_empty_n;
reg    msgStrm_read;
wire    ap_CS_fsm_state8;
wire   [127:0] msgLenStrm_dout;
wire    msgLenStrm_empty_n;
reg    msgLenStrm_read;
wire   [0:0] endMsgLenStrm_dout;
wire    endMsgLenStrm_empty_n;
reg    endMsgLenStrm_read;
wire   [127:0] outLenStrm_dout;
wire    outLenStrm_empty_n;
reg    outLenStrm_read;
wire   [0:0] endOutLenStrm_dout;
wire    endOutLenStrm_empty_n;
reg    endOutLenStrm_read;
wire    endDigestStrm_internal_full_n;
reg    endDigestStrm_internal_write;
reg   [63:0] word_fu_102;
wire   [63:0] select_ln68_1_fu_336_p3;
wire   [63:0] word_1_fu_348_p4;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [6:0] j_fu_106;
wire   [6:0] j_1_fu_306_p2;
wire    ap_block_pp0_stage0;
reg   [8:0] i_03_fu_110;
wire   [8:0] select_ln67_fu_270_p3;
reg   [14:0] indvar_flatten_fu_114;
wire   [14:0] add_ln67_fu_238_p2;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [63:0] trunc_ln81_fu_366_p1;
wire    ap_CS_fsm_state6;
reg    ap_block_state6;
wire   [0:0] endDigestStrm_internal_dout;
wire    endDigestStrm_internal_empty_n;
reg    endDigestStrm_internal_read;
wire    ap_CS_fsm_state9;
wire   [8:0] add_ln67_1_fu_264_p2;
wire   [6:0] select_ln68_fu_256_p3;
wire   [14:0] mul_fu_278_p3;
wire   [14:0] zext_ln70_fu_286_p1;
wire   [14:0] bit_idx_fu_294_p2;
wire   [63:0] word_1_fu_348_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [63:0] word_1_fu_348_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_shake_extensible_fu_195_ap_start_reg = 1'b0;
#0 word_fu_102 = 64'd0;
#0 j_fu_106 = 7'd0;
#0 i_03_fu_110 = 9'd0;
#0 indvar_flatten_fu_114 = 15'd0;
end

GenerateProof_shake_extensible grp_shake_extensible_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shake_extensible_fu_195_ap_start),
    .ap_done(grp_shake_extensible_fu_195_ap_done),
    .ap_idle(grp_shake_extensible_fu_195_ap_idle),
    .ap_ready(grp_shake_extensible_fu_195_ap_ready),
    .msgStrm_dout(msgStrm_dout),
    .msgStrm_empty_n(msgStrm_empty_n),
    .msgStrm_read(grp_shake_extensible_fu_195_msgStrm_read),
    .msgLenStrm_dout(msgLenStrm_dout),
    .msgLenStrm_empty_n(msgLenStrm_empty_n),
    .msgLenStrm_read(grp_shake_extensible_fu_195_msgLenStrm_read),
    .endMsgLenStrm_dout(endMsgLenStrm_dout),
    .endMsgLenStrm_empty_n(endMsgLenStrm_empty_n),
    .endMsgLenStrm_read(grp_shake_extensible_fu_195_endMsgLenStrm_read),
    .outLenStrm_dout(outLenStrm_dout),
    .outLenStrm_empty_n(outLenStrm_empty_n),
    .outLenStrm_read(grp_shake_extensible_fu_195_outLenStrm_read),
    .endOutLenStrm_dout(endOutLenStrm_dout),
    .endOutLenStrm_empty_n(endOutLenStrm_empty_n),
    .endOutLenStrm_read(grp_shake_extensible_fu_195_endOutLenStrm_read),
    .ch2_strm_din(grp_shake_extensible_fu_195_ch2_strm_din),
    .ch2_strm_full_n(ch2_strm_full_n),
    .ch2_strm_write(grp_shake_extensible_fu_195_ch2_strm_write),
    .ch2_strm_num_data_valid(3'd0),
    .ch2_strm_fifo_cap(3'd0),
    .endDigestStrm_internal_din(grp_shake_extensible_fu_195_endDigestStrm_internal_din),
    .endDigestStrm_internal_full_n(endDigestStrm_internal_full_n),
    .endDigestStrm_internal_write(grp_shake_extensible_fu_195_endDigestStrm_internal_write)
);

GenerateProof_bitset_64ns_64ns_6ns_1ns_64_1_1 #(
    .DATAWIDTH( 64 ),
    .ADDRWIDTH( 6 ))
bitset_64ns_64ns_6ns_1ns_64_1_1_U1912(
    .din(word_1_fu_348_p1),
    .sel(trunc_ln70_reg_457),
    .value(d_strm_cp_dout),
    .dout(word_1_fu_348_p4)
);

GenerateProof_fifo_w64_d2_S msgStrm_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(msgStrm_din),
    .if_full_n(msgStrm_full_n),
    .if_write(msgStrm_write),
    .if_dout(msgStrm_dout),
    .if_empty_n(msgStrm_empty_n),
    .if_read(msgStrm_read)
);

GenerateProof_fifo_w128_d2_S_x3 msgLenStrm_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(128'd2934),
    .if_full_n(msgLenStrm_full_n),
    .if_write(msgLenStrm_write),
    .if_dout(msgLenStrm_dout),
    .if_empty_n(msgLenStrm_empty_n),
    .if_read(msgLenStrm_read)
);

GenerateProof_fifo_w1_d2_S_x1 endMsgLenStrm_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(endMsgLenStrm_din),
    .if_full_n(endMsgLenStrm_full_n),
    .if_write(endMsgLenStrm_write),
    .if_dout(endMsgLenStrm_dout),
    .if_empty_n(endMsgLenStrm_empty_n),
    .if_read(endMsgLenStrm_read)
);

GenerateProof_fifo_w128_d2_S_x3 outLenStrm_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(128'd361168),
    .if_full_n(outLenStrm_full_n),
    .if_write(outLenStrm_write),
    .if_dout(outLenStrm_dout),
    .if_empty_n(outLenStrm_empty_n),
    .if_read(outLenStrm_read)
);

GenerateProof_fifo_w1_d2_S_x1 endOutLenStrm_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(endOutLenStrm_din),
    .if_full_n(endOutLenStrm_full_n),
    .if_write(endOutLenStrm_write),
    .if_dout(endOutLenStrm_dout),
    .if_empty_n(endOutLenStrm_empty_n),
    .if_read(endOutLenStrm_read)
);

GenerateProof_fifo_w1_d2_S_x1 endDigestStrm_internal_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_shake_extensible_fu_195_endDigestStrm_internal_din),
    .if_full_n(endDigestStrm_internal_full_n),
    .if_write(endDigestStrm_internal_write),
    .if_dout(endDigestStrm_internal_dout),
    .if_empty_n(endDigestStrm_internal_empty_n),
    .if_read(endDigestStrm_internal_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((endDigestStrm_internal_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shake_extensible_fu_195_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_shake_extensible_fu_195_ap_start_reg <= 1'b1;
        end else if ((grp_shake_extensible_fu_195_ap_ready == 1'b1)) begin
            grp_shake_extensible_fu_195_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_03_fu_110 <= 9'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln67_fu_232_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_03_fu_110 <= select_ln67_fu_270_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_114 <= 15'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln67_fu_232_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten_fu_114 <= add_ln67_fu_238_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_106 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln67_fu_232_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        j_fu_106 <= j_1_fu_306_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        word_fu_102 <= 64'd0;
    end else if (((icmp_ln73_reg_462 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_fu_102 <= word_1_fu_348_p4;
    end else if (((icmp_ln73_reg_462 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_fu_102 <= select_ln68_1_fu_336_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ch1_val_read_reg_407 <= ch1_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln70_1_reg_466 <= icmp_ln70_1_fu_312_p2;
        icmp_ln70_1_reg_466_pp0_iter1_reg <= icmp_ln70_1_reg_466;
        icmp_ln70_reg_452 <= icmp_ln70_fu_250_p2;
        icmp_ln73_reg_462 <= icmp_ln73_fu_300_p2;
        trunc_ln70_reg_457 <= trunc_ln70_fu_290_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_reg_470 <= {{ch1_val_read_reg_407[127:64]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_shake_extensible_fu_195_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((endDigestStrm_internal_empty_n == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln67_fu_232_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((endDigestStrm_internal_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((endDigestStrm_internal_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_462 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_strm_cp_blk_n = d_strm_cp_empty_n;
    end else begin
        d_strm_cp_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_462 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_strm_cp_read = 1'b1;
    end else begin
        d_strm_cp_read = 1'b0;
    end
end

always @ (*) begin
    if (((endDigestStrm_internal_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        endDigestStrm_internal_read = 1'b1;
    end else begin
        endDigestStrm_internal_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        endDigestStrm_internal_write = grp_shake_extensible_fu_195_endDigestStrm_internal_write;
    end else begin
        endDigestStrm_internal_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        endMsgLenStrm_din = 1'd1;
    end else if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        endMsgLenStrm_din = 1'd0;
    end else begin
        endMsgLenStrm_din = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        endMsgLenStrm_read = grp_shake_extensible_fu_195_endMsgLenStrm_read;
    end else begin
        endMsgLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6)) | ((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5)))) begin
        endMsgLenStrm_write = 1'b1;
    end else begin
        endMsgLenStrm_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        endOutLenStrm_din = 1'd1;
    end else if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        endOutLenStrm_din = 1'd0;
    end else begin
        endOutLenStrm_din = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        endOutLenStrm_read = grp_shake_extensible_fu_195_endOutLenStrm_read;
    end else begin
        endOutLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6)) | ((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5)))) begin
        endOutLenStrm_write = 1'b1;
    end else begin
        endOutLenStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        msgLenStrm_read = grp_shake_extensible_fu_195_msgLenStrm_read;
    end else begin
        msgLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        msgLenStrm_write = 1'b1;
    end else begin
        msgLenStrm_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        msgStrm_din = p_0_reg_470;
    end else if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        msgStrm_din = trunc_ln81_fu_366_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln70_1_reg_466_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001_grp1))) begin
        msgStrm_din = word_fu_102;
    end else begin
        msgStrm_din = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        msgStrm_read = grp_shake_extensible_fu_195_msgStrm_read;
    end else begin
        msgStrm_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln70_1_reg_466_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6)) | ((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5)))) begin
        msgStrm_write = 1'b1;
    end else begin
        msgStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        outLenStrm_read = grp_shake_extensible_fu_195_outLenStrm_read;
    end else begin
        outLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        outLenStrm_write = 1'b1;
    end else begin
        outLenStrm_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln67_fu_232_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln67_fu_232_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_shake_extensible_fu_195_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((endDigestStrm_internal_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_1_fu_264_p2 = (i_03_fu_110 + 9'd1);

assign add_ln67_fu_238_p2 = (indvar_flatten_fu_114 + 15'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1_grp1 = ((icmp_ln73_reg_462 == 1'd1) & (d_strm_cp_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2_grp1 = ((icmp_ln70_1_reg_466_pp0_iter1_reg == 1'd1) & (msgStrm_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((msgStrm_full_n == 1'b0) | (endOutLenStrm_full_n == 1'b0) | (endMsgLenStrm_full_n == 1'b0) | (outLenStrm_full_n == 1'b0) | (msgLenStrm_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((msgStrm_full_n == 1'b0) | (endOutLenStrm_full_n == 1'b0) | (endMsgLenStrm_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bit_idx_fu_294_p2 = (mul_fu_278_p3 + zext_ln70_fu_286_p1);

assign ch2_strm_din = grp_shake_extensible_fu_195_ch2_strm_din;

assign ch2_strm_write = grp_shake_extensible_fu_195_ch2_strm_write;

assign grp_shake_extensible_fu_195_ap_start = grp_shake_extensible_fu_195_ap_start_reg;

assign icmp_ln67_fu_232_p2 = ((indvar_flatten_fu_114 == 15'd23360) ? 1'b1 : 1'b0);

assign icmp_ln70_1_fu_312_p2 = ((j_1_fu_306_p2 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_250_p2 = ((j_fu_106 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_300_p2 = ((bit_idx_fu_294_p2 < 15'd23342) ? 1'b1 : 1'b0);

assign j_1_fu_306_p2 = (select_ln68_fu_256_p3 + 7'd1);

assign mul_fu_278_p3 = {{select_ln67_fu_270_p3}, {6'd0}};

assign select_ln67_fu_270_p3 = ((icmp_ln70_fu_250_p2[0:0] == 1'b1) ? add_ln67_1_fu_264_p2 : i_03_fu_110);

assign select_ln68_1_fu_336_p3 = ((icmp_ln70_reg_452[0:0] == 1'b1) ? 64'd0 : word_fu_102);

assign select_ln68_fu_256_p3 = ((icmp_ln70_fu_250_p2[0:0] == 1'b1) ? 7'd0 : j_fu_106);

assign trunc_ln70_fu_290_p1 = select_ln68_fu_256_p3[5:0];

assign trunc_ln81_fu_366_p1 = ch1_val_read_reg_407[63:0];

assign word_1_fu_348_p1 = ((icmp_ln70_reg_452[0:0] == 1'b1) ? 64'd0 : word_fu_102);

assign zext_ln70_fu_286_p1 = select_ln68_fu_256_p3;

endmodule //GenerateProof_chal2
