// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_GFMul2 (
        ap_ready,
        a,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [7:0] a;
output  [7:0] ap_return;
input   ap_rst;

wire   [7:0] a_2_fu_26_p2;
wire   [0:0] tmp_fu_18_p3;
wire   [7:0] a_1_fu_32_p2;

assign a_1_fu_32_p2 = (8'd27 ^ a_2_fu_26_p2);

assign a_2_fu_26_p2 = a << 8'd1;

assign ap_ready = 1'b1;

assign tmp_fu_18_p3 = a[32'd7];

assign ap_return = ((tmp_fu_18_p3[0:0] == 1'b1) ? a_1_fu_32_p2 : a_2_fu_26_p2);

endmodule //GenerateProof_GFMul2
