// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_mem_transfer_Pipeline_UNPACK_U (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s,
        u_1_address1,
        u_1_ce1,
        u_1_we1,
        u_1_d1,
        u_0_address1,
        u_0_ce1,
        u_0_we1,
        u_0_d1,
        tmp_79,
        u_t
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] s;
output  [17:0] u_1_address1;
output   u_1_ce1;
output   u_1_we1;
output  [0:0] u_1_d1;
output  [17:0] u_0_address1;
output   u_0_ce1;
output   u_0_we1;
output  [0:0] u_0_d1;
input  [14:0] tmp_79;
input  [255:0] u_t;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_fu_132_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln106_fu_172_p1;
wire   [0:0] icmp_ln106_fu_178_p2;
wire   [0:0] icmp_ln106_1_fu_201_p2;
reg   [8:0] b_fu_68;
wire   [8:0] add_ln103_fu_224_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_b_2;
reg    u_0_we1_local;
wire   [0:0] tmp_412_fu_184_p3;
reg    u_0_ce1_local;
reg    u_1_we1_local;
wire   [0:0] tmp_413_fu_215_p3;
reg    u_1_ce1_local;
wire   [14:0] zext_ln103_fu_140_p1;
wire   [6:0] lshr_ln_fu_154_p4;
wire   [13:0] or_ln_fu_164_p3;
wire   [14:0] add_ln105_fu_148_p2;
wire   [7:0] trunc_ln103_fu_144_p1;
wire   [14:0] or_ln1_fu_193_p3;
wire   [7:0] tmp_413_fu_215_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [0:0] tmp_412_fu_184_p0;
wire   [0:0] tmp_413_fu_215_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 b_fu_68 = 9'd0;
#0 ap_done_reg = 1'b0;
end

GenerateProof_bitselect_1ns_256ns_8ns_1_1_1 #(
    .DATAWIDTH( 256 ),
    .ADDRWIDTH( 8 ))
bitselect_1ns_256ns_8ns_1_1_1_U1099(
    .din(u_t),
    .sel(trunc_ln103_fu_144_p1),
    .dout(tmp_412_fu_184_p3)
);

GenerateProof_bitselect_1ns_256ns_8ns_1_1_1 #(
    .DATAWIDTH( 256 ),
    .ADDRWIDTH( 8 ))
bitselect_1ns_256ns_8ns_1_1_1_U1100(
    .din(u_t),
    .sel(tmp_413_fu_215_p2),
    .dout(tmp_413_fu_215_p3)
);

GenerateProof_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((tmp_fu_132_p3 == 1'd0)) begin
            b_fu_68 <= add_ln103_fu_224_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            b_fu_68 <= 9'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_132_p3 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_b_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_b_2 = b_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        u_0_ce1_local = 1'b1;
    end else begin
        u_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_fu_178_p2 == 1'd1) & (tmp_fu_132_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        u_0_we1_local = 1'b1;
    end else begin
        u_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        u_1_ce1_local = 1'b1;
    end else begin
        u_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_1_fu_201_p2 == 1'd1) & (tmp_fu_132_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        u_1_we1_local = 1'b1;
    end else begin
        u_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_fu_224_p2 = (ap_sig_allocacmp_b_2 + 9'd2);

assign add_ln105_fu_148_p2 = (tmp_79 + zext_ln103_fu_140_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln106_1_fu_201_p2 = ((or_ln1_fu_193_p3 < 15'd23614) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_178_p2 = ((add_ln105_fu_148_p2 < 15'd23614) ? 1'b1 : 1'b0);

assign lshr_ln_fu_154_p4 = {{ap_sig_allocacmp_b_2[7:1]}};

assign or_ln1_fu_193_p3 = {{s}, {trunc_ln103_fu_144_p1}};

assign or_ln_fu_164_p3 = {{s}, {lshr_ln_fu_154_p4}};

assign tmp_413_fu_215_p2 = {{lshr_ln_fu_154_p4}, {1'd1}};

assign tmp_fu_132_p3 = ap_sig_allocacmp_b_2[32'd8];

assign trunc_ln103_fu_144_p1 = ap_sig_allocacmp_b_2[7:0];

assign u_0_address1 = zext_ln106_fu_172_p1;

assign u_0_ce1 = u_0_ce1_local;

assign u_0_d1 = tmp_412_fu_184_p3;

assign u_0_we1 = u_0_we1_local;

assign u_1_address1 = zext_ln106_fu_172_p1;

assign u_1_ce1 = u_1_ce1_local;

assign u_1_d1 = tmp_413_fu_215_p3;

assign u_1_we1 = u_1_we1_local;

assign zext_ln103_fu_140_p1 = ap_sig_allocacmp_b_2;

assign zext_ln106_fu_172_p1 = or_ln_fu_164_p3;

endmodule //GenerateProof_mem_transfer_Pipeline_UNPACK_U
