// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        msgStrm_dout,
        msgStrm_empty_n,
        msgStrm_read,
        stateArray_i,
        stateArray_o,
        stateArray_o_ap_vld,
        stateArray_16_i,
        stateArray_16_o,
        stateArray_16_o_ap_vld,
        stateArray_15_i,
        stateArray_15_o,
        stateArray_15_o_ap_vld,
        stateArray_14_i,
        stateArray_14_o,
        stateArray_14_o_ap_vld,
        stateArray_13_i,
        stateArray_13_o,
        stateArray_13_o_ap_vld,
        stateArray_12_i,
        stateArray_12_o,
        stateArray_12_o_ap_vld,
        stateArray_11_i,
        stateArray_11_o,
        stateArray_11_o_ap_vld,
        stateArray_10_i,
        stateArray_10_o,
        stateArray_10_o_ap_vld,
        stateArray_9_i,
        stateArray_9_o,
        stateArray_9_o_ap_vld,
        stateArray_8_i,
        stateArray_8_o,
        stateArray_8_o_ap_vld,
        stateArray_7_i,
        stateArray_7_o,
        stateArray_7_o_ap_vld,
        stateArray_6_i,
        stateArray_6_o,
        stateArray_6_o_ap_vld,
        stateArray_5_i,
        stateArray_5_o,
        stateArray_5_o_ap_vld,
        stateArray_4_i,
        stateArray_4_o,
        stateArray_4_o_ap_vld,
        stateArray_3_i,
        stateArray_3_o,
        stateArray_3_o_ap_vld,
        stateArray_2_i,
        stateArray_2_o,
        stateArray_2_o_ap_vld,
        stateArray_1_i,
        stateArray_1_o,
        stateArray_1_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] msgStrm_dout;
input   msgStrm_empty_n;
output   msgStrm_read;
input  [63:0] stateArray_i;
output  [63:0] stateArray_o;
output   stateArray_o_ap_vld;
input  [63:0] stateArray_16_i;
output  [63:0] stateArray_16_o;
output   stateArray_16_o_ap_vld;
input  [63:0] stateArray_15_i;
output  [63:0] stateArray_15_o;
output   stateArray_15_o_ap_vld;
input  [63:0] stateArray_14_i;
output  [63:0] stateArray_14_o;
output   stateArray_14_o_ap_vld;
input  [63:0] stateArray_13_i;
output  [63:0] stateArray_13_o;
output   stateArray_13_o_ap_vld;
input  [63:0] stateArray_12_i;
output  [63:0] stateArray_12_o;
output   stateArray_12_o_ap_vld;
input  [63:0] stateArray_11_i;
output  [63:0] stateArray_11_o;
output   stateArray_11_o_ap_vld;
input  [63:0] stateArray_10_i;
output  [63:0] stateArray_10_o;
output   stateArray_10_o_ap_vld;
input  [63:0] stateArray_9_i;
output  [63:0] stateArray_9_o;
output   stateArray_9_o_ap_vld;
input  [63:0] stateArray_8_i;
output  [63:0] stateArray_8_o;
output   stateArray_8_o_ap_vld;
input  [63:0] stateArray_7_i;
output  [63:0] stateArray_7_o;
output   stateArray_7_o_ap_vld;
input  [63:0] stateArray_6_i;
output  [63:0] stateArray_6_o;
output   stateArray_6_o_ap_vld;
input  [63:0] stateArray_5_i;
output  [63:0] stateArray_5_o;
output   stateArray_5_o_ap_vld;
input  [63:0] stateArray_4_i;
output  [63:0] stateArray_4_o;
output   stateArray_4_o_ap_vld;
input  [63:0] stateArray_3_i;
output  [63:0] stateArray_3_o;
output   stateArray_3_o_ap_vld;
input  [63:0] stateArray_2_i;
output  [63:0] stateArray_2_o;
output   stateArray_2_o_ap_vld;
input  [63:0] stateArray_1_i;
output  [63:0] stateArray_1_o;
output   stateArray_1_o_ap_vld;

reg ap_idle;
reg msgStrm_read;
reg[63:0] stateArray_o;
reg stateArray_o_ap_vld;
reg[63:0] stateArray_16_o;
reg stateArray_16_o_ap_vld;
reg[63:0] stateArray_15_o;
reg stateArray_15_o_ap_vld;
reg[63:0] stateArray_14_o;
reg stateArray_14_o_ap_vld;
reg[63:0] stateArray_13_o;
reg stateArray_13_o_ap_vld;
reg[63:0] stateArray_12_o;
reg stateArray_12_o_ap_vld;
reg[63:0] stateArray_11_o;
reg stateArray_11_o_ap_vld;
reg[63:0] stateArray_10_o;
reg stateArray_10_o_ap_vld;
reg[63:0] stateArray_9_o;
reg stateArray_9_o_ap_vld;
reg[63:0] stateArray_8_o;
reg stateArray_8_o_ap_vld;
reg[63:0] stateArray_7_o;
reg stateArray_7_o_ap_vld;
reg[63:0] stateArray_6_o;
reg stateArray_6_o_ap_vld;
reg[63:0] stateArray_5_o;
reg stateArray_5_o_ap_vld;
reg[63:0] stateArray_4_o;
reg stateArray_4_o_ap_vld;
reg[63:0] stateArray_3_o;
reg stateArray_3_o_ap_vld;
reg[63:0] stateArray_2_o;
reg stateArray_2_o_ap_vld;
reg[63:0] stateArray_1_o;
reg stateArray_1_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln453_fu_343_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    msgStrm_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [4:0] i_3_reg_500;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] i_fu_104;
wire   [4:0] add_ln453_fu_349_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_3;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [63:0] stateArray_133_fu_435_p2;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [63:0] tmp_s_fu_360_p35;
wire   [63:0] tmp_s_fu_360_p37;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_s_fu_360_p1;
wire   [4:0] tmp_s_fu_360_p3;
wire   [4:0] tmp_s_fu_360_p5;
wire   [4:0] tmp_s_fu_360_p7;
wire   [4:0] tmp_s_fu_360_p9;
wire   [4:0] tmp_s_fu_360_p11;
wire   [4:0] tmp_s_fu_360_p13;
wire   [4:0] tmp_s_fu_360_p15;
wire   [4:0] tmp_s_fu_360_p17;
wire   [4:0] tmp_s_fu_360_p19;
wire   [4:0] tmp_s_fu_360_p21;
wire   [4:0] tmp_s_fu_360_p23;
wire   [4:0] tmp_s_fu_360_p25;
wire   [4:0] tmp_s_fu_360_p27;
wire   [4:0] tmp_s_fu_360_p29;
wire   [4:0] tmp_s_fu_360_p31;
wire  signed [4:0] tmp_s_fu_360_p33;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_104 = 5'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) GenerateProof_sparsemux_35_5_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 64 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 64 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 64 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 64 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 64 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 64 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 64 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 64 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 64 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 64 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 64 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 64 ))
sparsemux_35_5_64_1_1_U77(
    .din0(stateArray_i),
    .din1(stateArray_1_i),
    .din2(stateArray_2_i),
    .din3(stateArray_3_i),
    .din4(stateArray_4_i),
    .din5(stateArray_5_i),
    .din6(stateArray_6_i),
    .din7(stateArray_7_i),
    .din8(stateArray_8_i),
    .din9(stateArray_9_i),
    .din10(stateArray_10_i),
    .din11(stateArray_11_i),
    .din12(stateArray_12_i),
    .din13(stateArray_13_i),
    .din14(stateArray_14_i),
    .din15(stateArray_15_i),
    .din16(stateArray_16_i),
    .def(tmp_s_fu_360_p35),
    .sel(i_3_reg_500),
    .dout(tmp_s_fu_360_p37)
);

GenerateProof_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln453_fu_343_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_104 <= add_ln453_fu_349_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_104 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_3_reg_500 <= ap_sig_allocacmp_i_3;
    end
end

always @ (*) begin
    if (((icmp_ln453_fu_343_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        msgStrm_blk_n = msgStrm_empty_n;
    end else begin
        msgStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        msgStrm_read = 1'b1;
    end else begin
        msgStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd10))) begin
        stateArray_10_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_10_o = stateArray_10_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd10))) begin
        stateArray_10_o_ap_vld = 1'b1;
    end else begin
        stateArray_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd11))) begin
        stateArray_11_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_11_o = stateArray_11_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd11))) begin
        stateArray_11_o_ap_vld = 1'b1;
    end else begin
        stateArray_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd12))) begin
        stateArray_12_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_12_o = stateArray_12_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd12))) begin
        stateArray_12_o_ap_vld = 1'b1;
    end else begin
        stateArray_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd13))) begin
        stateArray_13_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_13_o = stateArray_13_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd13))) begin
        stateArray_13_o_ap_vld = 1'b1;
    end else begin
        stateArray_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd14))) begin
        stateArray_14_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_14_o = stateArray_14_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd14))) begin
        stateArray_14_o_ap_vld = 1'b1;
    end else begin
        stateArray_14_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd15))) begin
        stateArray_15_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_15_o = stateArray_15_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd15))) begin
        stateArray_15_o_ap_vld = 1'b1;
    end else begin
        stateArray_15_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(i_3_reg_500 == 5'd0) & ~(i_3_reg_500 == 5'd1) & ~(i_3_reg_500 == 5'd2) & ~(i_3_reg_500 == 5'd3) & ~(i_3_reg_500 == 5'd4) & ~(i_3_reg_500 == 5'd5) & ~(i_3_reg_500 == 5'd6) & ~(i_3_reg_500 == 5'd7) & ~(i_3_reg_500 == 5'd8) & ~(i_3_reg_500 == 5'd9) & ~(i_3_reg_500 == 5'd10) & ~(i_3_reg_500 == 5'd11) & ~(i_3_reg_500 == 5'd12) & ~(i_3_reg_500 == 5'd13) & ~(i_3_reg_500 == 5'd14) & ~(i_3_reg_500 == 5'd15) & (1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stateArray_16_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_16_o = stateArray_16_i;
    end
end

always @ (*) begin
    if ((~(i_3_reg_500 == 5'd0) & ~(i_3_reg_500 == 5'd1) & ~(i_3_reg_500 == 5'd2) & ~(i_3_reg_500 == 5'd3) & ~(i_3_reg_500 == 5'd4) & ~(i_3_reg_500 == 5'd5) & ~(i_3_reg_500 == 5'd6) & ~(i_3_reg_500 == 5'd7) & ~(i_3_reg_500 == 5'd8) & ~(i_3_reg_500 == 5'd9) & ~(i_3_reg_500 == 5'd10) & ~(i_3_reg_500 == 5'd11) & ~(i_3_reg_500 == 5'd12) & ~(i_3_reg_500 == 5'd13) & ~(i_3_reg_500 == 5'd14) & ~(i_3_reg_500 == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stateArray_16_o_ap_vld = 1'b1;
    end else begin
        stateArray_16_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd1))) begin
        stateArray_1_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_1_o = stateArray_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd1))) begin
        stateArray_1_o_ap_vld = 1'b1;
    end else begin
        stateArray_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd2))) begin
        stateArray_2_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_2_o = stateArray_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd2))) begin
        stateArray_2_o_ap_vld = 1'b1;
    end else begin
        stateArray_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd3))) begin
        stateArray_3_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_3_o = stateArray_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd3))) begin
        stateArray_3_o_ap_vld = 1'b1;
    end else begin
        stateArray_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd4))) begin
        stateArray_4_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_4_o = stateArray_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd4))) begin
        stateArray_4_o_ap_vld = 1'b1;
    end else begin
        stateArray_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd5))) begin
        stateArray_5_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_5_o = stateArray_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd5))) begin
        stateArray_5_o_ap_vld = 1'b1;
    end else begin
        stateArray_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd6))) begin
        stateArray_6_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_6_o = stateArray_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd6))) begin
        stateArray_6_o_ap_vld = 1'b1;
    end else begin
        stateArray_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd7))) begin
        stateArray_7_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_7_o = stateArray_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd7))) begin
        stateArray_7_o_ap_vld = 1'b1;
    end else begin
        stateArray_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd8))) begin
        stateArray_8_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_8_o = stateArray_8_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd8))) begin
        stateArray_8_o_ap_vld = 1'b1;
    end else begin
        stateArray_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd9))) begin
        stateArray_9_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_9_o = stateArray_9_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd9))) begin
        stateArray_9_o_ap_vld = 1'b1;
    end else begin
        stateArray_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd0))) begin
        stateArray_o = stateArray_133_fu_435_p2;
    end else begin
        stateArray_o = stateArray_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_reg_500 == 5'd0))) begin
        stateArray_o_ap_vld = 1'b1;
    end else begin
        stateArray_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln453_fu_349_p2 = (ap_sig_allocacmp_i_3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((msgStrm_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((msgStrm_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((msgStrm_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((msgStrm_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln453_fu_343_p2 = ((ap_sig_allocacmp_i_3 == 5'd17) ? 1'b1 : 1'b0);

assign stateArray_133_fu_435_p2 = (tmp_s_fu_360_p37 ^ msgStrm_dout);

assign tmp_s_fu_360_p35 = 'bx;

endmodule //GenerateProof_shakeXOF_32u_Pipeline_LOOP_GEN_FULL_MESSAGE_BLK
