-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_tree_expansion is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    root_val : IN STD_LOGIC_VECTOR (127 downto 0);
    iv_val1 : IN STD_LOGIC_VECTOR (127 downto 0);
    k_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    k_strm_full_n : IN STD_LOGIC;
    k_strm_write : OUT STD_LOGIC;
    k_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    k_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    leaf_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    leaf_strm_full_n : IN STD_LOGIC;
    leaf_strm_write : OUT STD_LOGIC;
    leaf_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    leaf_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of GenerateProof_tree_expansion is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal k_strm_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal leaf_strm_blk_n : STD_LOGIC;
    signal iv_val1_read_reg_81 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal root_val_read_reg_86 : STD_LOGIC_VECTOR (127 downto 0);
    signal left_reg_92 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal grp_PRG3538_fu_60_ap_done : STD_LOGIC;
    signal right_reg_97 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_PRG3538_fu_60_ap_start : STD_LOGIC;
    signal grp_PRG3538_fu_60_ap_idle : STD_LOGIC;
    signal grp_PRG3538_fu_60_ap_ready : STD_LOGIC;
    signal grp_PRG3538_fu_60_ap_return_0 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_PRG3538_fu_60_ap_return_1 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_PRG3538_fu_60_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call7 : BOOLEAN;
    signal ap_block_state3 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GenerateProof_PRG3538 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        iv_val : IN STD_LOGIC_VECTOR (127 downto 0);
        seed : IN STD_LOGIC_VECTOR (127 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;



begin
    grp_PRG3538_fu_60 : component GenerateProof_PRG3538
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_PRG3538_fu_60_ap_start,
        ap_done => grp_PRG3538_fu_60_ap_done,
        ap_idle => grp_PRG3538_fu_60_ap_idle,
        ap_ready => grp_PRG3538_fu_60_ap_ready,
        iv_val => iv_val1_read_reg_81,
        seed => root_val_read_reg_86,
        ap_return_0 => grp_PRG3538_fu_60_ap_return_0,
        ap_return_1 => grp_PRG3538_fu_60_ap_return_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((k_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_PRG3538_fu_60_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_PRG3538_fu_60_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call7) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_PRG3538_fu_60_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_PRG3538_fu_60_ap_ready = ap_const_logic_1)) then 
                    grp_PRG3538_fu_60_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                iv_val1_read_reg_81 <= iv_val1;
                root_val_read_reg_86 <= root_val;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_PRG3538_fu_60_ap_done = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                left_reg_92 <= grp_PRG3538_fu_60_ap_return_0;
                right_reg_97 <= grp_PRG3538_fu_60_ap_return_1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, k_strm_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state1, ap_block_state2, grp_PRG3538_fu_60_ap_done, ap_block_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((grp_PRG3538_fu_60_ap_done = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((k_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2, grp_PRG3538_fu_60_ap_done)
    begin
        if (((grp_PRG3538_fu_60_ap_done = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(k_strm_full_n)
    begin
        if ((k_strm_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call7_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call7 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(k_strm_full_n, leaf_strm_full_n)
    begin
                ap_block_state2 <= ((leaf_strm_full_n = ap_const_logic_0) or (k_strm_full_n = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(k_strm_full_n, leaf_strm_full_n)
    begin
                ap_block_state3 <= ((leaf_strm_full_n = ap_const_logic_0) or (k_strm_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, k_strm_full_n, ap_CS_fsm_state4)
    begin
        if (((k_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_PRG3538_fu_60_ap_start <= grp_PRG3538_fu_60_ap_start_reg;

    internal_ap_ready_assign_proc : process(k_strm_full_n, ap_CS_fsm_state4)
    begin
        if (((k_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    k_strm_blk_n_assign_proc : process(k_strm_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            k_strm_blk_n <= k_strm_full_n;
        else 
            k_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    k_strm_din_assign_proc : process(k_strm_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, root_val_read_reg_86, left_reg_92, ap_block_state2, grp_PRG3538_fu_60_ap_done, right_reg_97, ap_block_state3)
    begin
        if (((k_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            k_strm_din <= right_reg_97;
        elsif (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            k_strm_din <= left_reg_92;
        elsif ((not(((grp_PRG3538_fu_60_ap_done = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            k_strm_din <= root_val_read_reg_86;
        else 
            k_strm_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    k_strm_write_assign_proc : process(k_strm_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2, grp_PRG3538_fu_60_ap_done, ap_block_state3)
    begin
        if (((not(((grp_PRG3538_fu_60_ap_done = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((k_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            k_strm_write <= ap_const_logic_1;
        else 
            k_strm_write <= ap_const_logic_0;
        end if; 
    end process;


    leaf_strm_blk_n_assign_proc : process(leaf_strm_full_n, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            leaf_strm_blk_n <= leaf_strm_full_n;
        else 
            leaf_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    leaf_strm_din_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_block_state2, grp_PRG3538_fu_60_ap_done, right_reg_97, grp_PRG3538_fu_60_ap_return_0, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            leaf_strm_din <= right_reg_97;
        elsif ((not(((grp_PRG3538_fu_60_ap_done = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            leaf_strm_din <= grp_PRG3538_fu_60_ap_return_0;
        else 
            leaf_strm_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    leaf_strm_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_block_state2, grp_PRG3538_fu_60_ap_done, ap_block_state3)
    begin
        if (((not(((grp_PRG3538_fu_60_ap_done = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            leaf_strm_write <= ap_const_logic_1;
        else 
            leaf_strm_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
