-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_mem_transfer_Pipeline_UNPACK_U is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (6 downto 0);
    u_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_1_ce1 : OUT STD_LOGIC;
    u_1_we1 : OUT STD_LOGIC;
    u_1_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    u_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_0_ce1 : OUT STD_LOGIC;
    u_0_we1 : OUT STD_LOGIC;
    u_0_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    tmp_79 : IN STD_LOGIC_VECTOR (14 downto 0);
    u_t : IN STD_LOGIC_VECTOR (255 downto 0) );
end;


architecture behav of GenerateProof_mem_transfer_Pipeline_UNPACK_U is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv15_5C3E : STD_LOGIC_VECTOR (14 downto 0) := "101110000111110";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_fu_132_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln106_fu_172_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln106_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_1_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_fu_68 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln103_fu_224_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_b_2 : STD_LOGIC_VECTOR (8 downto 0);
    signal u_0_we1_local : STD_LOGIC;
    signal tmp_412_fu_184_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal u_0_ce1_local : STD_LOGIC;
    signal u_1_we1_local : STD_LOGIC;
    signal tmp_413_fu_215_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal u_1_ce1_local : STD_LOGIC;
    signal zext_ln103_fu_140_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal lshr_ln_fu_154_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln_fu_164_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln105_fu_148_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln103_fu_144_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln1_fu_193_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_413_fu_215_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_412_fu_184_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_413_fu_215_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component GenerateProof_bitselect_1ns_256ns_8ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (255 downto 0);
        sel : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component GenerateProof_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    bitselect_1ns_256ns_8ns_1_1_1_U1099 : component GenerateProof_bitselect_1ns_256ns_8ns_1_1_1
    generic map (
        DATAWIDTH => 256,
        ADDRWIDTH => 8)
    port map (
        din => u_t,
        sel => trunc_ln103_fu_144_p1,
        dout => tmp_412_fu_184_p3);

    bitselect_1ns_256ns_8ns_1_1_1_U1100 : component GenerateProof_bitselect_1ns_256ns_8ns_1_1_1
    generic map (
        DATAWIDTH => 256,
        ADDRWIDTH => 8)
    port map (
        din => u_t,
        sel => tmp_413_fu_215_p2,
        dout => tmp_413_fu_215_p3);

    flow_control_loop_pipe_sequential_init_U : component GenerateProof_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    b_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((tmp_fu_132_p3 = ap_const_lv1_0)) then 
                    b_fu_68 <= add_ln103_fu_224_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    b_fu_68 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln103_fu_224_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_b_2) + unsigned(ap_const_lv9_2));
    add_ln105_fu_148_p2 <= std_logic_vector(unsigned(tmp_79) + unsigned(zext_ln103_fu_140_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_132_p3)
    begin
        if (((tmp_fu_132_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_b_2_assign_proc : process(ap_CS_fsm_state1, b_fu_68, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_b_2 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_b_2 <= b_fu_68;
        end if; 
    end process;

    icmp_ln106_1_fu_201_p2 <= "1" when (unsigned(or_ln1_fu_193_p3) < unsigned(ap_const_lv15_5C3E)) else "0";
    icmp_ln106_fu_178_p2 <= "1" when (unsigned(add_ln105_fu_148_p2) < unsigned(ap_const_lv15_5C3E)) else "0";
    lshr_ln_fu_154_p4 <= ap_sig_allocacmp_b_2(7 downto 1);
    or_ln1_fu_193_p3 <= (s & trunc_ln103_fu_144_p1);
    or_ln_fu_164_p3 <= (s & lshr_ln_fu_154_p4);
    tmp_413_fu_215_p2 <= (lshr_ln_fu_154_p4 & ap_const_lv1_1);
    tmp_fu_132_p3 <= ap_sig_allocacmp_b_2(8 downto 8);
    trunc_ln103_fu_144_p1 <= ap_sig_allocacmp_b_2(8 - 1 downto 0);
    u_0_address1 <= zext_ln106_fu_172_p1(18 - 1 downto 0);
    u_0_ce1 <= u_0_ce1_local;

    u_0_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            u_0_ce1_local <= ap_const_logic_1;
        else 
            u_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    u_0_d1 <= tmp_412_fu_184_p3;
    u_0_we1 <= u_0_we1_local;

    u_0_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_132_p3, icmp_ln106_fu_178_p2)
    begin
        if (((icmp_ln106_fu_178_p2 = ap_const_lv1_1) and (tmp_fu_132_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            u_0_we1_local <= ap_const_logic_1;
        else 
            u_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    u_1_address1 <= zext_ln106_fu_172_p1(18 - 1 downto 0);
    u_1_ce1 <= u_1_ce1_local;

    u_1_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            u_1_ce1_local <= ap_const_logic_1;
        else 
            u_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    u_1_d1 <= tmp_413_fu_215_p3;
    u_1_we1 <= u_1_we1_local;

    u_1_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_132_p3, icmp_ln106_1_fu_201_p2)
    begin
        if (((icmp_ln106_1_fu_201_p2 = ap_const_lv1_1) and (tmp_fu_132_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            u_1_we1_local <= ap_const_logic_1;
        else 
            u_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln103_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_b_2),15));
    zext_ln106_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_164_p3),64));
end behav;
