-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_expand_seed is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    iv_val : IN STD_LOGIC_VECTOR (127 downto 0);
    seed_strm_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    seed_strm_empty_n : IN STD_LOGIC;
    seed_strm_read : OUT STD_LOGIC;
    r_strm_0_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    r_strm_0_full_n : IN STD_LOGIC;
    r_strm_0_write : OUT STD_LOGIC;
    r_strm_0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    r_strm_0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    r_strm_1_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    r_strm_1_full_n : IN STD_LOGIC;
    r_strm_1_write : OUT STD_LOGIC;
    r_strm_1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    r_strm_1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of GenerateProof_expand_seed is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal iv_val_read_reg_179 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal sd_load_reg_197 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sd_load_1_reg_202 : STD_LOGIC_VECTOR (127 downto 0);
    signal sd_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sd_ce0 : STD_LOGIC;
    signal sd_we0 : STD_LOGIC;
    signal sd_q0 : STD_LOGIC_VECTOR (127 downto 0);
    signal sd_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sd_q1 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_done : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_idle : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_ready : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_seed_strm_read : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_ce0 : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_we0 : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_d0 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start : STD_LOGIC;
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_done : STD_LOGIC;
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_idle : STD_LOGIC;
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_ready : STD_LOGIC;
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_0_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_0_write : STD_LOGIC;
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_1_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_1_write : STD_LOGIC;
    signal grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln16_fu_127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal t_fu_56 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal t_7_fu_133_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sd_ce1_local : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sd_ce0_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GenerateProof_expand_seed_Pipeline_READ_SEEDS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        seed_strm_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        seed_strm_empty_n : IN STD_LOGIC;
        seed_strm_read : OUT STD_LOGIC;
        sd_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        sd_ce0 : OUT STD_LOGIC;
        sd_we0 : OUT STD_LOGIC;
        sd_d0 : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component GenerateProof_expand_seed_Pipeline_PROCESS_CHUNKS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        r_strm_0_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        r_strm_0_full_n : IN STD_LOGIC;
        r_strm_0_write : OUT STD_LOGIC;
        r_strm_0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        r_strm_0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        r_strm_1_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        r_strm_1_full_n : IN STD_LOGIC;
        r_strm_1_write : OUT STD_LOGIC;
        r_strm_1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        r_strm_1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        iv_val : IN STD_LOGIC_VECTOR (127 downto 0);
        sd_load : IN STD_LOGIC_VECTOR (127 downto 0);
        sd_load_1 : IN STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component GenerateProof_expand_seed_sd_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (127 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (127 downto 0);
        address1 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;



begin
    sd_U : component GenerateProof_expand_seed_sd_RAM_AUTO_1R1W
    generic map (
        DataWidth => 128,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sd_address0,
        ce0 => sd_ce0,
        we0 => sd_we0,
        d0 => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_d0,
        q0 => sd_q0,
        address1 => sd_address1,
        ce1 => sd_ce1_local,
        q1 => sd_q1);

    grp_expand_seed_Pipeline_READ_SEEDS_fu_95 : component GenerateProof_expand_seed_Pipeline_READ_SEEDS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start,
        ap_done => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_done,
        ap_idle => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_idle,
        ap_ready => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_ready,
        seed_strm_dout => seed_strm_dout,
        seed_strm_empty_n => seed_strm_empty_n,
        seed_strm_read => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_seed_strm_read,
        sd_address0 => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_address0,
        sd_ce0 => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_ce0,
        sd_we0 => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_we0,
        sd_d0 => grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_d0);

    grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102 : component GenerateProof_expand_seed_Pipeline_PROCESS_CHUNKS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start,
        ap_done => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_done,
        ap_idle => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_idle,
        ap_ready => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_ready,
        r_strm_0_din => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_0_din,
        r_strm_0_full_n => r_strm_0_full_n,
        r_strm_0_write => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_0_write,
        r_strm_0_num_data_valid => r_strm_0_num_data_valid,
        r_strm_0_fifo_cap => r_strm_0_fifo_cap,
        r_strm_1_din => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_1_din,
        r_strm_1_full_n => r_strm_1_full_n,
        r_strm_1_write => grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_1_write,
        r_strm_1_num_data_valid => r_strm_1_num_data_valid,
        r_strm_1_fifo_cap => r_strm_1_fifo_cap,
        iv_val => iv_val_read_reg_179,
        sd_load => sd_load_reg_197,
        sd_load_1 => sd_load_1_reg_202);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln16_fu_127_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_ready = ap_const_logic_1)) then 
                    grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln16_fu_127_p2 = ap_const_lv1_0))) then 
                    grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_ready = ap_const_logic_1)) then 
                    grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_fu_56 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln16_fu_127_p2 = ap_const_lv1_0))) then 
                t_fu_56 <= t_7_fu_133_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                iv_val_read_reg_179 <= iv_val;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                sd_load_1_reg_202 <= sd_q0;
                sd_load_reg_197 <= sd_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_done, grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_done, ap_CS_fsm_state2, icmp_ln16_fu_127_p2, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln16_fu_127_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_done)
    begin
        if ((grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_done)
    begin
        if ((grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln16_fu_127_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln16_fu_127_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start <= grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_ap_start_reg;
    grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start <= grp_expand_seed_Pipeline_READ_SEEDS_fu_95_ap_start_reg;
    icmp_ln16_fu_127_p2 <= "1" when (t_fu_56 = ap_const_lv8_80) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln16_fu_127_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln16_fu_127_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    r_strm_0_din <= grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_0_din;
    r_strm_0_write <= grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_0_write;
    r_strm_1_din <= grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_1_din;
    r_strm_1_write <= grp_expand_seed_Pipeline_PROCESS_CHUNKS_fu_102_r_strm_1_write;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    sd_address0_assign_proc : process(grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            sd_address0 <= grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_address0;
        else 
            sd_address0 <= ap_const_lv64_1(1 - 1 downto 0);
        end if; 
    end process;

    sd_address1 <= ap_const_lv64_0(1 - 1 downto 0);

    sd_ce0_assign_proc : process(grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_ce0, ap_CS_fsm_state3, sd_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            sd_ce0 <= grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_ce0;
        else 
            sd_ce0 <= sd_ce0_local;
        end if; 
    end process;


    sd_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sd_ce0_local <= ap_const_logic_1;
        else 
            sd_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    sd_ce1_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sd_ce1_local <= ap_const_logic_1;
        else 
            sd_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    sd_we0_assign_proc : process(grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            sd_we0 <= grp_expand_seed_Pipeline_READ_SEEDS_fu_95_sd_we0;
        else 
            sd_we0 <= ap_const_logic_0;
        end if; 
    end process;

    seed_strm_read <= grp_expand_seed_Pipeline_READ_SEEDS_fu_95_seed_strm_read;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    t_7_fu_133_p2 <= std_logic_vector(unsigned(t_fu_56) + unsigned(ap_const_lv8_1));
end behav;
