-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_EvalCircuit is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    u_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_0_ce0 : OUT STD_LOGIC;
    u_0_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    u_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_0_ce1 : OUT STD_LOGIC;
    u_0_we1 : OUT STD_LOGIC;
    u_0_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    u_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_1_ce0 : OUT STD_LOGIC;
    u_1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    u_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    u_1_ce1 : OUT STD_LOGIC;
    u_1_we1 : OUT STD_LOGIC;
    u_1_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_0_ce0 : OUT STD_LOGIC;
    V_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_0_ce1 : OUT STD_LOGIC;
    V_0_we1 : OUT STD_LOGIC;
    V_0_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    V_0_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_1_ce0 : OUT STD_LOGIC;
    V_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    V_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    V_1_ce1 : OUT STD_LOGIC;
    V_1_we1 : OUT STD_LOGIC;
    V_1_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    V_1_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    witness_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    witness_TVALID : IN STD_LOGIC;
    witness_TREADY : OUT STD_LOGIC;
    circuit_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    circuit_TVALID : IN STD_LOGIC;
    circuit_TREADY : OUT STD_LOGIC;
    d_strm_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    d_strm_TVALID : OUT STD_LOGIC;
    d_strm_TREADY : IN STD_LOGIC;
    d_strm_cp_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    d_strm_cp_full_n : IN STD_LOGIC;
    d_strm_cp_write : OUT STD_LOGIC;
    d_strm_cp_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    d_strm_cp_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    a0_strm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    a0_strm_full_n : IN STD_LOGIC;
    a0_strm_write : OUT STD_LOGIC;
    a0_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    a0_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    a1_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    a1_strm_full_n : IN STD_LOGIC;
    a1_strm_write : OUT STD_LOGIC;
    a1_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    a1_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of GenerateProof_EvalCircuit is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal extended_witness_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal extended_witness_ce0 : STD_LOGIC;
    signal extended_witness_we0 : STD_LOGIC;
    signal extended_witness_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal extended_witness_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal extended_witness_ce1 : STD_LOGIC;
    signal extended_witness_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_done : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_idle : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_ready : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TREADY : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_din : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_write : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_witness_TREADY : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_we0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TVALID : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_idle : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_ready : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TVALID : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TREADY : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_din : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_write : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_ce1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_we1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_d1 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_ce1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_we1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_d1 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a0_strm_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a0_strm_write : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a1_strm_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a1_strm_write : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_circuit_TREADY : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_we0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_address1 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_we1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_d1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce0 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_address1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_we1 : STD_LOGIC;
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_d1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal d_strm_TDATA_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GenerateProof_EvalCircuit_Pipeline_VITIS_LOOP_100_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        witness_TVALID : IN STD_LOGIC;
        d_strm_TREADY : IN STD_LOGIC;
        d_strm_cp_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        d_strm_cp_full_n : IN STD_LOGIC;
        d_strm_cp_write : OUT STD_LOGIC;
        d_strm_cp_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        d_strm_cp_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        witness_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        witness_TREADY : OUT STD_LOGIC;
        extended_witness_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        extended_witness_ce0 : OUT STD_LOGIC;
        extended_witness_we0 : OUT STD_LOGIC;
        extended_witness_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        u_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_0_ce0 : OUT STD_LOGIC;
        u_0_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        u_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_1_ce0 : OUT STD_LOGIC;
        u_1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        d_strm_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        d_strm_TVALID : OUT STD_LOGIC );
    end component;


    component GenerateProof_EvalCircuit_Pipeline_VITIS_LOOP_107_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d_strm_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        d_strm_TVALID : OUT STD_LOGIC;
        d_strm_TREADY : IN STD_LOGIC;
        d_strm_cp_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        d_strm_cp_full_n : IN STD_LOGIC;
        d_strm_cp_write : OUT STD_LOGIC;
        d_strm_cp_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        d_strm_cp_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        V_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_0_ce0 : OUT STD_LOGIC;
        V_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        V_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_0_ce1 : OUT STD_LOGIC;
        V_0_we1 : OUT STD_LOGIC;
        V_0_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
        V_0_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
        V_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_1_ce0 : OUT STD_LOGIC;
        V_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
        V_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        V_1_ce1 : OUT STD_LOGIC;
        V_1_we1 : OUT STD_LOGIC;
        V_1_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
        V_1_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
        a0_strm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        a0_strm_full_n : IN STD_LOGIC;
        a0_strm_write : OUT STD_LOGIC;
        a0_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        a0_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        a1_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        a1_strm_full_n : IN STD_LOGIC;
        a1_strm_write : OUT STD_LOGIC;
        a1_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        a1_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        circuit_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        circuit_TVALID : IN STD_LOGIC;
        circuit_TREADY : OUT STD_LOGIC;
        extended_witness_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        extended_witness_ce0 : OUT STD_LOGIC;
        extended_witness_we0 : OUT STD_LOGIC;
        extended_witness_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        extended_witness_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        extended_witness_address1 : OUT STD_LOGIC_VECTOR (18 downto 0);
        extended_witness_ce1 : OUT STD_LOGIC;
        extended_witness_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
        u_0_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_0_ce0 : OUT STD_LOGIC;
        u_0_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        u_0_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_0_ce1 : OUT STD_LOGIC;
        u_0_we1 : OUT STD_LOGIC;
        u_0_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        u_1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_1_ce0 : OUT STD_LOGIC;
        u_1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        u_1_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        u_1_ce1 : OUT STD_LOGIC;
        u_1_we1 : OUT STD_LOGIC;
        u_1_d1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component GenerateProof_EvalCircuit_extended_witness_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    extended_witness_U : component GenerateProof_EvalCircuit_extended_witness_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 271187,
        AddressWidth => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => extended_witness_address0,
        ce0 => extended_witness_ce0,
        we0 => extended_witness_we0,
        d0 => extended_witness_d0,
        q0 => extended_witness_q0,
        address1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_address1,
        ce1 => extended_witness_ce1,
        q1 => extended_witness_q1);

    grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56 : component GenerateProof_EvalCircuit_Pipeline_VITIS_LOOP_100_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start,
        ap_done => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_done,
        ap_idle => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_idle,
        ap_ready => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_ready,
        witness_TVALID => witness_TVALID,
        d_strm_TREADY => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TREADY,
        d_strm_cp_din => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_din,
        d_strm_cp_full_n => d_strm_cp_full_n,
        d_strm_cp_write => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_write,
        d_strm_cp_num_data_valid => ap_const_lv3_0,
        d_strm_cp_fifo_cap => ap_const_lv3_0,
        witness_TDATA => witness_TDATA,
        witness_TREADY => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_witness_TREADY,
        extended_witness_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_address0,
        extended_witness_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_ce0,
        extended_witness_we0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_we0,
        extended_witness_d0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_d0,
        u_0_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_address0,
        u_0_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_ce0,
        u_0_q0 => u_0_q0,
        u_1_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_address0,
        u_1_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_ce0,
        u_1_q0 => u_1_q0,
        d_strm_TDATA => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TDATA,
        d_strm_TVALID => grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TVALID);

    grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72 : component GenerateProof_EvalCircuit_Pipeline_VITIS_LOOP_107_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start,
        ap_done => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done,
        ap_idle => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_idle,
        ap_ready => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_ready,
        d_strm_TDATA => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TDATA,
        d_strm_TVALID => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TVALID,
        d_strm_TREADY => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TREADY,
        d_strm_cp_din => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_din,
        d_strm_cp_full_n => d_strm_cp_full_n,
        d_strm_cp_write => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_write,
        d_strm_cp_num_data_valid => ap_const_lv3_0,
        d_strm_cp_fifo_cap => ap_const_lv3_0,
        V_0_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_address0,
        V_0_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_ce0,
        V_0_q0 => V_0_q0,
        V_0_address1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_address1,
        V_0_ce1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_ce1,
        V_0_we1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_we1,
        V_0_d1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_d1,
        V_0_q1 => V_0_q1,
        V_1_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_address0,
        V_1_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_ce0,
        V_1_q0 => V_1_q0,
        V_1_address1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_address1,
        V_1_ce1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_ce1,
        V_1_we1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_we1,
        V_1_d1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_d1,
        V_1_q1 => V_1_q1,
        a0_strm_din => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a0_strm_din,
        a0_strm_full_n => a0_strm_full_n,
        a0_strm_write => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a0_strm_write,
        a0_strm_num_data_valid => ap_const_lv3_0,
        a0_strm_fifo_cap => ap_const_lv3_0,
        a1_strm_din => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a1_strm_din,
        a1_strm_full_n => a1_strm_full_n,
        a1_strm_write => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a1_strm_write,
        a1_strm_num_data_valid => ap_const_lv3_0,
        a1_strm_fifo_cap => ap_const_lv3_0,
        circuit_TDATA => circuit_TDATA,
        circuit_TVALID => circuit_TVALID,
        circuit_TREADY => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_circuit_TREADY,
        extended_witness_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_address0,
        extended_witness_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce0,
        extended_witness_we0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_we0,
        extended_witness_d0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_d0,
        extended_witness_q0 => extended_witness_q0,
        extended_witness_address1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_address1,
        extended_witness_ce1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce1,
        extended_witness_q1 => extended_witness_q1,
        u_0_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_address0,
        u_0_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce0,
        u_0_q0 => u_0_q0,
        u_0_address1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_address1,
        u_0_ce1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce1,
        u_0_we1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_we1,
        u_0_d1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_d1,
        u_1_address0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_address0,
        u_1_ce0 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce0,
        u_1_q0 => u_1_q0,
        u_1_address1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_address1,
        u_1_ce1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce1,
        u_1_we1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_we1,
        u_1_d1 => grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_ready = ap_const_logic_1)) then 
                    grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    d_strm_TDATA_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TVALID = ap_const_logic_1))) then 
                d_strm_TDATA_reg <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TDATA;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TVALID = ap_const_logic_1))) then 
                d_strm_TDATA_reg <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TDATA;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_done, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    V_0_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_address0;
    V_0_address1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_address1;
    V_0_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_ce0;
    V_0_ce1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_ce1;
    V_0_d1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_d1;
    V_0_we1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_0_we1;
    V_1_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_address0;
    V_1_address1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_address1;
    V_1_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_ce0;
    V_1_ce1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_ce1;
    V_1_d1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_d1;
    V_1_we1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_V_1_we1;
    a0_strm_din <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a0_strm_din;
    a0_strm_write <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a0_strm_write;
    a1_strm_din <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a1_strm_din;
    a1_strm_write <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_a1_strm_write;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_done)
    begin
        if ((grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done)
    begin
        if ((grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done = ap_const_logic_1)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    circuit_TREADY_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_circuit_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            circuit_TREADY <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_circuit_TREADY;
        else 
            circuit_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    d_strm_TDATA_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TDATA, grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TVALID, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TDATA, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TVALID, ap_CS_fsm_state2, d_strm_TDATA_reg, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TVALID = ap_const_logic_1))) then 
            d_strm_TDATA <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TDATA;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TVALID = ap_const_logic_1))) then 
            d_strm_TDATA <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TDATA;
        else 
            d_strm_TDATA <= d_strm_TDATA_reg;
        end if; 
    end process;


    d_strm_TVALID_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TVALID, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_strm_TVALID <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TVALID;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            d_strm_TVALID <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TVALID;
        else 
            d_strm_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    d_strm_cp_din_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_din, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_din, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_strm_cp_din <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            d_strm_cp_din <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_din;
        else 
            d_strm_cp_din <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_din;
        end if; 
    end process;


    d_strm_cp_write_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_write, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_write, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_strm_cp_write <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_cp_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            d_strm_cp_write <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_cp_write;
        else 
            d_strm_cp_write <= ap_const_logic_0;
        end if; 
    end process;


    extended_witness_address0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_address0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            extended_witness_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            extended_witness_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_address0;
        else 
            extended_witness_address0 <= "XXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    extended_witness_ce0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_ce0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            extended_witness_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            extended_witness_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_ce0;
        else 
            extended_witness_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    extended_witness_ce1_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            extended_witness_ce1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_ce1;
        else 
            extended_witness_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    extended_witness_d0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_d0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            extended_witness_d0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            extended_witness_d0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_d0;
        else 
            extended_witness_d0 <= "X";
        end if; 
    end process;


    extended_witness_we0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_we0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            extended_witness_we0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_extended_witness_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            extended_witness_we0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_extended_witness_we0;
        else 
            extended_witness_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_ap_start_reg;
    grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_d_strm_TREADY <= (d_strm_TREADY and ap_CS_fsm_state2);
    grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_ap_start_reg;
    grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_d_strm_TREADY <= (d_strm_TREADY and ap_CS_fsm_state4);

    u_0_address0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_address0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_0_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            u_0_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_address0;
        else 
            u_0_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    u_0_address1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_address1;

    u_0_ce0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_ce0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_0_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            u_0_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_0_ce0;
        else 
            u_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    u_0_ce1_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_0_ce1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_ce1;
        else 
            u_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    u_0_d1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_d1;

    u_0_we1_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_we1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_0_we1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_0_we1;
        else 
            u_0_we1 <= ap_const_logic_0;
        end if; 
    end process;


    u_1_address0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_address0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_1_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            u_1_address0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_address0;
        else 
            u_1_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    u_1_address1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_address1;

    u_1_ce0_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_ce0, grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_1_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            u_1_ce0 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_u_1_ce0;
        else 
            u_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    u_1_ce1_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_1_ce1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_ce1;
        else 
            u_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    u_1_d1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_d1;

    u_1_we1_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_we1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            u_1_we1 <= grp_EvalCircuit_Pipeline_VITIS_LOOP_107_2_fu_72_u_1_we1;
        else 
            u_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    witness_TREADY_assign_proc : process(grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_witness_TREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            witness_TREADY <= grp_EvalCircuit_Pipeline_VITIS_LOOP_100_1_fu_56_witness_TREADY;
        else 
            witness_TREADY <= ap_const_logic_0;
        end if; 
    end process;

end behav;
