-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GenerateProof_encrypt36 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r : IN STD_LOGIC_VECTOR (127 downto 0);
    key : IN STD_LOGIC_VECTOR (127 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of GenerateProof_encrypt36 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal cipher_key_list_reg_132 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_1_reg_137 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_2_reg_142 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_3_reg_147 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_4_reg_152 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_5_reg_157 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_6_reg_162 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_7_reg_167 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_8_reg_172 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_9_reg_177 : STD_LOGIC_VECTOR (127 downto 0);
    signal cipher_key_list_11_reg_182 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_0 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_1 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_2 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_3 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_4 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_5 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_6 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_7 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_8 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_9 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_return_10 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_updateKey_fu_40_ap_ce : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_process37_fu_48_ap_start : STD_LOGIC;
    signal grp_process37_fu_48_ap_done : STD_LOGIC;
    signal grp_process37_fu_48_ap_idle : STD_LOGIC;
    signal grp_process37_fu_48_ap_ready : STD_LOGIC;
    signal grp_process37_fu_48_ap_return : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_process37_fu_48_ap_start_reg : STD_LOGIC := '0';
    signal ap_return_preg : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GenerateProof_updateKey IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        cipherkey : IN STD_LOGIC_VECTOR (127 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component GenerateProof_process37 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        this_1_0_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_1_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_2_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_3_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_4_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_5_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_6_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_7_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_8_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_9_val : IN STD_LOGIC_VECTOR (127 downto 0);
        this_1_10_val : IN STD_LOGIC_VECTOR (127 downto 0);
        plaintext : IN STD_LOGIC_VECTOR (127 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;



begin
    grp_updateKey_fu_40 : component GenerateProof_updateKey
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        cipherkey => key,
        ap_return_0 => grp_updateKey_fu_40_ap_return_0,
        ap_return_1 => grp_updateKey_fu_40_ap_return_1,
        ap_return_2 => grp_updateKey_fu_40_ap_return_2,
        ap_return_3 => grp_updateKey_fu_40_ap_return_3,
        ap_return_4 => grp_updateKey_fu_40_ap_return_4,
        ap_return_5 => grp_updateKey_fu_40_ap_return_5,
        ap_return_6 => grp_updateKey_fu_40_ap_return_6,
        ap_return_7 => grp_updateKey_fu_40_ap_return_7,
        ap_return_8 => grp_updateKey_fu_40_ap_return_8,
        ap_return_9 => grp_updateKey_fu_40_ap_return_9,
        ap_return_10 => grp_updateKey_fu_40_ap_return_10,
        ap_ce => grp_updateKey_fu_40_ap_ce);

    grp_process37_fu_48 : component GenerateProof_process37
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_process37_fu_48_ap_start,
        ap_done => grp_process37_fu_48_ap_done,
        ap_idle => grp_process37_fu_48_ap_idle,
        ap_ready => grp_process37_fu_48_ap_ready,
        this_1_0_val => cipher_key_list_reg_132,
        this_1_1_val => cipher_key_list_1_reg_137,
        this_1_2_val => cipher_key_list_2_reg_142,
        this_1_3_val => cipher_key_list_3_reg_147,
        this_1_4_val => cipher_key_list_4_reg_152,
        this_1_5_val => cipher_key_list_5_reg_157,
        this_1_6_val => cipher_key_list_6_reg_162,
        this_1_7_val => cipher_key_list_7_reg_167,
        this_1_8_val => cipher_key_list_8_reg_172,
        this_1_9_val => cipher_key_list_9_reg_177,
        this_1_10_val => cipher_key_list_11_reg_182,
        plaintext => in_r,
        ap_return => grp_process37_fu_48_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv128_lc_1;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_process37_fu_48_ap_done = ap_const_logic_1))) then 
                    ap_return_preg <= grp_process37_fu_48_ap_return;
                end if; 
            end if;
        end if;
    end process;


    grp_process37_fu_48_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process37_fu_48_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_process37_fu_48_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process37_fu_48_ap_ready = ap_const_logic_1)) then 
                    grp_process37_fu_48_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                cipher_key_list_11_reg_182 <= grp_updateKey_fu_40_ap_return_10;
                cipher_key_list_1_reg_137 <= grp_updateKey_fu_40_ap_return_1;
                cipher_key_list_2_reg_142 <= grp_updateKey_fu_40_ap_return_2;
                cipher_key_list_3_reg_147 <= grp_updateKey_fu_40_ap_return_3;
                cipher_key_list_4_reg_152 <= grp_updateKey_fu_40_ap_return_4;
                cipher_key_list_5_reg_157 <= grp_updateKey_fu_40_ap_return_5;
                cipher_key_list_6_reg_162 <= grp_updateKey_fu_40_ap_return_6;
                cipher_key_list_7_reg_167 <= grp_updateKey_fu_40_ap_return_7;
                cipher_key_list_8_reg_172 <= grp_updateKey_fu_40_ap_return_8;
                cipher_key_list_9_reg_177 <= grp_updateKey_fu_40_ap_return_9;
                cipher_key_list_reg_132 <= grp_updateKey_fu_40_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state13, grp_process37_fu_48_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_process37_fu_48_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_process37_fu_48_ap_done)
    begin
        if ((grp_process37_fu_48_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state13, grp_process37_fu_48_ap_done)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_process37_fu_48_ap_done = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13, grp_process37_fu_48_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_process37_fu_48_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state13, grp_process37_fu_48_ap_done, grp_process37_fu_48_ap_return, ap_return_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_process37_fu_48_ap_done = ap_const_logic_1))) then 
            ap_return <= grp_process37_fu_48_ap_return;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    grp_process37_fu_48_ap_start <= grp_process37_fu_48_ap_start_reg;

    grp_updateKey_fu_40_ap_ce_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            grp_updateKey_fu_40_ap_ce <= ap_const_logic_0;
        else 
            grp_updateKey_fu_40_ap_ce <= ap_const_logic_1;
        end if; 
    end process;

end behav;
