// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_ProverCircuitEval_Block_entry_u_0_arg_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        u_0_address0,
        u_0_ce0,
        u_0_q0,
        u_0_address1,
        u_0_ce1,
        u_0_we1,
        u_0_d1,
        u_1_address0,
        u_1_ce0,
        u_1_q0,
        u_1_address1,
        u_1_ce1,
        u_1_we1,
        u_1_d1,
        V_0_address0,
        V_0_ce0,
        V_0_q0,
        V_0_address1,
        V_0_ce1,
        V_0_we1,
        V_0_d1,
        V_0_q1,
        V_1_address0,
        V_1_ce0,
        V_1_q0,
        V_1_address1,
        V_1_ce1,
        V_1_we1,
        V_1_d1,
        V_1_q1,
        witness_TDATA,
        witness_TVALID,
        witness_TREADY,
        circuit_TDATA,
        circuit_TVALID,
        circuit_TREADY,
        d_strm_TDATA,
        d_strm_TVALID,
        d_strm_TREADY,
        d_strm_cp_din,
        d_strm_cp_full_n,
        d_strm_cp_write,
        d_strm_cp_num_data_valid,
        d_strm_cp_fifo_cap,
        a0_strm_din,
        a0_strm_full_n,
        a0_strm_write,
        a0_strm_num_data_valid,
        a0_strm_fifo_cap,
        a1_strm_din,
        a1_strm_full_n,
        a1_strm_write,
        a1_strm_num_data_valid,
        a1_strm_fifo_cap,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [17:0] u_0_address0;
output   u_0_ce0;
input  [0:0] u_0_q0;
output  [17:0] u_0_address1;
output   u_0_ce1;
output   u_0_we1;
output  [0:0] u_0_d1;
output  [17:0] u_1_address0;
output   u_1_ce0;
input  [0:0] u_1_q0;
output  [17:0] u_1_address1;
output   u_1_ce1;
output   u_1_we1;
output  [0:0] u_1_d1;
output  [17:0] V_0_address0;
output   V_0_ce0;
input  [127:0] V_0_q0;
output  [17:0] V_0_address1;
output   V_0_ce1;
output   V_0_we1;
output  [127:0] V_0_d1;
input  [127:0] V_0_q1;
output  [17:0] V_1_address0;
output   V_1_ce0;
input  [127:0] V_1_q0;
output  [17:0] V_1_address1;
output   V_1_ce1;
output   V_1_we1;
output  [127:0] V_1_d1;
input  [127:0] V_1_q1;
input  [7:0] witness_TDATA;
input   witness_TVALID;
output   witness_TREADY;
input  [127:0] circuit_TDATA;
input   circuit_TVALID;
output   circuit_TREADY;
output  [7:0] d_strm_TDATA;
output   d_strm_TVALID;
input   d_strm_TREADY;
output  [0:0] d_strm_cp_din;
input   d_strm_cp_full_n;
output   d_strm_cp_write;
input  [2:0] d_strm_cp_num_data_valid;
input  [2:0] d_strm_cp_fifo_cap;
output  [255:0] a0_strm_din;
input   a0_strm_full_n;
output   a0_strm_write;
input  [2:0] a0_strm_num_data_valid;
input  [2:0] a0_strm_fifo_cap;
output  [127:0] a1_strm_din;
input   a1_strm_full_n;
output   a1_strm_write;
input  [2:0] a1_strm_num_data_valid;
input  [2:0] a1_strm_fifo_cap;
output  [127:0] ap_return_0;
output  [127:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg start_write;
reg[17:0] u_0_address0;
reg u_0_ce0;
reg u_0_ce1;
reg u_0_we1;
reg[17:0] u_1_address0;
reg u_1_ce0;
reg u_1_ce1;
reg u_1_we1;
reg[17:0] V_0_address0;
reg V_0_ce0;
reg V_0_ce1;
reg V_0_we1;
reg[17:0] V_1_address0;
reg V_1_ce0;
reg V_1_ce1;
reg V_1_we1;
reg witness_TREADY;
reg circuit_TREADY;
reg[7:0] d_strm_TDATA;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [127:0] grp_compute_mask_fu_48_ap_return_0;
wire   [127:0] grp_compute_mask_fu_48_ap_return_1;
reg   [127:0] call_ret_reg_84_0;
reg   [127:0] call_ret_reg_84_1;
wire    ap_CS_fsm_state2;
wire    grp_compute_mask_fu_48_ap_done;
wire    grp_compute_mask_fu_48_ap_start;
wire    grp_compute_mask_fu_48_ap_idle;
wire    grp_compute_mask_fu_48_ap_ready;
wire   [17:0] grp_compute_mask_fu_48_u_0_address0;
wire    grp_compute_mask_fu_48_u_0_ce0;
wire   [17:0] grp_compute_mask_fu_48_u_1_address0;
wire    grp_compute_mask_fu_48_u_1_ce0;
wire   [17:0] grp_compute_mask_fu_48_V_0_address0;
wire    grp_compute_mask_fu_48_V_0_ce0;
wire   [17:0] grp_compute_mask_fu_48_V_1_address0;
wire    grp_compute_mask_fu_48_V_1_ce0;
wire    grp_EvalCircuit_fu_60_ap_start;
wire    grp_EvalCircuit_fu_60_ap_done;
wire    grp_EvalCircuit_fu_60_ap_idle;
wire    grp_EvalCircuit_fu_60_ap_ready;
wire   [17:0] grp_EvalCircuit_fu_60_u_0_address0;
wire    grp_EvalCircuit_fu_60_u_0_ce0;
wire   [17:0] grp_EvalCircuit_fu_60_u_0_address1;
wire    grp_EvalCircuit_fu_60_u_0_ce1;
wire    grp_EvalCircuit_fu_60_u_0_we1;
wire   [0:0] grp_EvalCircuit_fu_60_u_0_d1;
wire   [17:0] grp_EvalCircuit_fu_60_u_1_address0;
wire    grp_EvalCircuit_fu_60_u_1_ce0;
wire   [17:0] grp_EvalCircuit_fu_60_u_1_address1;
wire    grp_EvalCircuit_fu_60_u_1_ce1;
wire    grp_EvalCircuit_fu_60_u_1_we1;
wire   [0:0] grp_EvalCircuit_fu_60_u_1_d1;
wire   [17:0] grp_EvalCircuit_fu_60_V_0_address0;
wire    grp_EvalCircuit_fu_60_V_0_ce0;
wire   [17:0] grp_EvalCircuit_fu_60_V_0_address1;
wire    grp_EvalCircuit_fu_60_V_0_ce1;
wire    grp_EvalCircuit_fu_60_V_0_we1;
wire   [127:0] grp_EvalCircuit_fu_60_V_0_d1;
wire   [17:0] grp_EvalCircuit_fu_60_V_1_address0;
wire    grp_EvalCircuit_fu_60_V_1_ce0;
wire   [17:0] grp_EvalCircuit_fu_60_V_1_address1;
wire    grp_EvalCircuit_fu_60_V_1_ce1;
wire    grp_EvalCircuit_fu_60_V_1_we1;
wire   [127:0] grp_EvalCircuit_fu_60_V_1_d1;
wire    grp_EvalCircuit_fu_60_witness_TREADY;
wire    grp_EvalCircuit_fu_60_circuit_TREADY;
wire   [7:0] grp_EvalCircuit_fu_60_d_strm_TDATA;
wire    grp_EvalCircuit_fu_60_d_strm_TVALID;
wire    grp_EvalCircuit_fu_60_d_strm_TREADY;
wire   [0:0] grp_EvalCircuit_fu_60_d_strm_cp_din;
wire    grp_EvalCircuit_fu_60_d_strm_cp_write;
wire   [255:0] grp_EvalCircuit_fu_60_a0_strm_din;
wire    grp_EvalCircuit_fu_60_a0_strm_write;
wire   [127:0] grp_EvalCircuit_fu_60_a1_strm_din;
wire    grp_EvalCircuit_fu_60_a1_strm_write;
reg    grp_compute_mask_fu_48_ap_start_reg;
reg    ap_block_state1_ignore_call10;
reg    grp_EvalCircuit_fu_60_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] d_strm_TDATA_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_compute_mask_fu_48_ap_start_reg = 1'b0;
#0 grp_EvalCircuit_fu_60_ap_start_reg = 1'b0;
end

GenerateProof_compute_mask grp_compute_mask_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mask_fu_48_ap_start),
    .ap_done(grp_compute_mask_fu_48_ap_done),
    .ap_idle(grp_compute_mask_fu_48_ap_idle),
    .ap_ready(grp_compute_mask_fu_48_ap_ready),
    .u_0_address0(grp_compute_mask_fu_48_u_0_address0),
    .u_0_ce0(grp_compute_mask_fu_48_u_0_ce0),
    .u_0_q0(u_0_q0),
    .u_1_address0(grp_compute_mask_fu_48_u_1_address0),
    .u_1_ce0(grp_compute_mask_fu_48_u_1_ce0),
    .u_1_q0(u_1_q0),
    .V_0_address0(grp_compute_mask_fu_48_V_0_address0),
    .V_0_ce0(grp_compute_mask_fu_48_V_0_ce0),
    .V_0_q0(V_0_q0),
    .V_1_address0(grp_compute_mask_fu_48_V_1_address0),
    .V_1_ce0(grp_compute_mask_fu_48_V_1_ce0),
    .V_1_q0(V_1_q0),
    .ap_return_0(grp_compute_mask_fu_48_ap_return_0),
    .ap_return_1(grp_compute_mask_fu_48_ap_return_1)
);

GenerateProof_EvalCircuit grp_EvalCircuit_fu_60(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_EvalCircuit_fu_60_ap_start),
    .ap_done(grp_EvalCircuit_fu_60_ap_done),
    .ap_idle(grp_EvalCircuit_fu_60_ap_idle),
    .ap_ready(grp_EvalCircuit_fu_60_ap_ready),
    .u_0_address0(grp_EvalCircuit_fu_60_u_0_address0),
    .u_0_ce0(grp_EvalCircuit_fu_60_u_0_ce0),
    .u_0_q0(u_0_q0),
    .u_0_address1(grp_EvalCircuit_fu_60_u_0_address1),
    .u_0_ce1(grp_EvalCircuit_fu_60_u_0_ce1),
    .u_0_we1(grp_EvalCircuit_fu_60_u_0_we1),
    .u_0_d1(grp_EvalCircuit_fu_60_u_0_d1),
    .u_1_address0(grp_EvalCircuit_fu_60_u_1_address0),
    .u_1_ce0(grp_EvalCircuit_fu_60_u_1_ce0),
    .u_1_q0(u_1_q0),
    .u_1_address1(grp_EvalCircuit_fu_60_u_1_address1),
    .u_1_ce1(grp_EvalCircuit_fu_60_u_1_ce1),
    .u_1_we1(grp_EvalCircuit_fu_60_u_1_we1),
    .u_1_d1(grp_EvalCircuit_fu_60_u_1_d1),
    .V_0_address0(grp_EvalCircuit_fu_60_V_0_address0),
    .V_0_ce0(grp_EvalCircuit_fu_60_V_0_ce0),
    .V_0_q0(V_0_q0),
    .V_0_address1(grp_EvalCircuit_fu_60_V_0_address1),
    .V_0_ce1(grp_EvalCircuit_fu_60_V_0_ce1),
    .V_0_we1(grp_EvalCircuit_fu_60_V_0_we1),
    .V_0_d1(grp_EvalCircuit_fu_60_V_0_d1),
    .V_0_q1(V_0_q1),
    .V_1_address0(grp_EvalCircuit_fu_60_V_1_address0),
    .V_1_ce0(grp_EvalCircuit_fu_60_V_1_ce0),
    .V_1_q0(V_1_q0),
    .V_1_address1(grp_EvalCircuit_fu_60_V_1_address1),
    .V_1_ce1(grp_EvalCircuit_fu_60_V_1_ce1),
    .V_1_we1(grp_EvalCircuit_fu_60_V_1_we1),
    .V_1_d1(grp_EvalCircuit_fu_60_V_1_d1),
    .V_1_q1(V_1_q1),
    .witness_TDATA(witness_TDATA),
    .witness_TVALID(witness_TVALID),
    .witness_TREADY(grp_EvalCircuit_fu_60_witness_TREADY),
    .circuit_TDATA(circuit_TDATA),
    .circuit_TVALID(circuit_TVALID),
    .circuit_TREADY(grp_EvalCircuit_fu_60_circuit_TREADY),
    .d_strm_TDATA(grp_EvalCircuit_fu_60_d_strm_TDATA),
    .d_strm_TVALID(grp_EvalCircuit_fu_60_d_strm_TVALID),
    .d_strm_TREADY(grp_EvalCircuit_fu_60_d_strm_TREADY),
    .d_strm_cp_din(grp_EvalCircuit_fu_60_d_strm_cp_din),
    .d_strm_cp_full_n(d_strm_cp_full_n),
    .d_strm_cp_write(grp_EvalCircuit_fu_60_d_strm_cp_write),
    .d_strm_cp_num_data_valid(3'd0),
    .d_strm_cp_fifo_cap(3'd0),
    .a0_strm_din(grp_EvalCircuit_fu_60_a0_strm_din),
    .a0_strm_full_n(a0_strm_full_n),
    .a0_strm_write(grp_EvalCircuit_fu_60_a0_strm_write),
    .a0_strm_num_data_valid(3'd0),
    .a0_strm_fifo_cap(3'd0),
    .a1_strm_din(grp_EvalCircuit_fu_60_a1_strm_din),
    .a1_strm_full_n(a1_strm_full_n),
    .a1_strm_write(grp_EvalCircuit_fu_60_a1_strm_write),
    .a1_strm_num_data_valid(3'd0),
    .a1_strm_fifo_cap(3'd0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (grp_EvalCircuit_fu_60_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_EvalCircuit_fu_60_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_EvalCircuit_fu_60_ap_start_reg <= 1'b1;
        end else if ((grp_EvalCircuit_fu_60_ap_ready == 1'b1)) begin
            grp_EvalCircuit_fu_60_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mask_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call10) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mask_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mask_fu_48_ap_ready == 1'b1)) begin
            grp_compute_mask_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_compute_mask_fu_48_ap_done == 1'b1))) begin
        call_ret_reg_84_0 <= grp_compute_mask_fu_48_ap_return_0;
        call_ret_reg_84_1 <= grp_compute_mask_fu_48_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_EvalCircuit_fu_60_d_strm_TVALID == 1'b1))) begin
        d_strm_TDATA_reg <= grp_EvalCircuit_fu_60_d_strm_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_0_address0 = grp_EvalCircuit_fu_60_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        V_0_address0 = grp_compute_mask_fu_48_V_0_address0;
    end else begin
        V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_0_ce0 = grp_EvalCircuit_fu_60_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        V_0_ce0 = grp_compute_mask_fu_48_V_0_ce0;
    end else begin
        V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_0_ce1 = grp_EvalCircuit_fu_60_V_0_ce1;
    end else begin
        V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_0_we1 = grp_EvalCircuit_fu_60_V_0_we1;
    end else begin
        V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_1_address0 = grp_EvalCircuit_fu_60_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        V_1_address0 = grp_compute_mask_fu_48_V_1_address0;
    end else begin
        V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_1_ce0 = grp_EvalCircuit_fu_60_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        V_1_ce0 = grp_compute_mask_fu_48_V_1_ce0;
    end else begin
        V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_1_ce1 = grp_EvalCircuit_fu_60_V_1_ce1;
    end else begin
        V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_1_we1 = grp_EvalCircuit_fu_60_V_1_we1;
    end else begin
        V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_mask_fu_48_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_EvalCircuit_fu_60_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_EvalCircuit_fu_60_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        circuit_TREADY = grp_EvalCircuit_fu_60_circuit_TREADY;
    end else begin
        circuit_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_EvalCircuit_fu_60_d_strm_TVALID == 1'b1))) begin
        d_strm_TDATA = grp_EvalCircuit_fu_60_d_strm_TDATA;
    end else begin
        d_strm_TDATA = d_strm_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_EvalCircuit_fu_60_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_0_address0 = grp_EvalCircuit_fu_60_u_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_0_address0 = grp_compute_mask_fu_48_u_0_address0;
    end else begin
        u_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_0_ce0 = grp_EvalCircuit_fu_60_u_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_0_ce0 = grp_compute_mask_fu_48_u_0_ce0;
    end else begin
        u_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_0_ce1 = grp_EvalCircuit_fu_60_u_0_ce1;
    end else begin
        u_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_0_we1 = grp_EvalCircuit_fu_60_u_0_we1;
    end else begin
        u_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_1_address0 = grp_EvalCircuit_fu_60_u_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_1_address0 = grp_compute_mask_fu_48_u_1_address0;
    end else begin
        u_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_1_ce0 = grp_EvalCircuit_fu_60_u_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        u_1_ce0 = grp_compute_mask_fu_48_u_1_ce0;
    end else begin
        u_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_1_ce1 = grp_EvalCircuit_fu_60_u_1_ce1;
    end else begin
        u_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u_1_we1 = grp_EvalCircuit_fu_60_u_1_we1;
    end else begin
        u_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        witness_TREADY = grp_EvalCircuit_fu_60_witness_TREADY;
    end else begin
        witness_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_compute_mask_fu_48_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_EvalCircuit_fu_60_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign V_0_address1 = grp_EvalCircuit_fu_60_V_0_address1;

assign V_0_d1 = grp_EvalCircuit_fu_60_V_0_d1;

assign V_1_address1 = grp_EvalCircuit_fu_60_V_1_address1;

assign V_1_d1 = grp_EvalCircuit_fu_60_V_1_d1;

assign a0_strm_din = grp_EvalCircuit_fu_60_a0_strm_din;

assign a0_strm_write = grp_EvalCircuit_fu_60_a0_strm_write;

assign a1_strm_din = grp_EvalCircuit_fu_60_a1_strm_din;

assign a1_strm_write = grp_EvalCircuit_fu_60_a1_strm_write;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call10 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign ap_return_0 = call_ret_reg_84_0;

assign ap_return_1 = call_ret_reg_84_1;

assign d_strm_TVALID = grp_EvalCircuit_fu_60_d_strm_TVALID;

assign d_strm_cp_din = grp_EvalCircuit_fu_60_d_strm_cp_din;

assign d_strm_cp_write = grp_EvalCircuit_fu_60_d_strm_cp_write;

assign grp_EvalCircuit_fu_60_ap_start = grp_EvalCircuit_fu_60_ap_start_reg;

assign grp_EvalCircuit_fu_60_d_strm_TREADY = (d_strm_TREADY & ap_CS_fsm_state4);

assign grp_compute_mask_fu_48_ap_start = grp_compute_mask_fu_48_ap_start_reg;

assign start_out = real_start;

assign u_0_address1 = grp_EvalCircuit_fu_60_u_0_address1;

assign u_0_d1 = grp_EvalCircuit_fu_60_u_0_d1;

assign u_1_address1 = grp_EvalCircuit_fu_60_u_1_address1;

assign u_1_d1 = grp_EvalCircuit_fu_60_u_1_d1;

endmodule //GenerateProof_ProverCircuitEval_Block_entry_u_0_arg_proc
