// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module GenerateProof_PRG_1 (
        ap_clk,
        ap_rst,
        iv_val,
        seed,
        ap_return_0,
        ap_return_1,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [127:0] iv_val;
input  [127:0] seed;
output  [127:0] ap_return_0;
output  [127:0] ap_return_1;
input   ap_ce;

reg[127:0] ap_return_0;
reg[127:0] ap_return_1;

wire    ap_block_pp0_stage0_11001;
wire   [127:0] grp_encrypt_fu_28_ap_return;
reg    grp_encrypt_fu_28_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp27;
wire   [127:0] grp_encrypt_fu_40_key;
wire   [127:0] grp_encrypt_fu_40_ap_return;
reg    grp_encrypt_fu_40_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp29;
wire    ap_block_pp0_stage0_ignoreCallOp27;
wire    ap_block_pp0_stage0_ignoreCallOp29;
wire    ap_block_pp0_stage0;
reg    ap_ce_reg;
reg   [127:0] iv_val_int_reg;
reg   [127:0] seed_int_reg;
reg   [127:0] ap_return_0_int_reg;
reg   [127:0] ap_return_1_int_reg;

GenerateProof_encrypt grp_encrypt_fu_28(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .in_r(seed_int_reg),
    .key(iv_val_int_reg),
    .ap_return(grp_encrypt_fu_28_ap_return),
    .ap_ce(grp_encrypt_fu_28_ap_ce)
);

GenerateProof_encrypt grp_encrypt_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .in_r(seed_int_reg),
    .key(grp_encrypt_fu_40_key),
    .ap_return(grp_encrypt_fu_40_ap_return),
    .ap_ce(grp_encrypt_fu_40_ap_ce)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= grp_encrypt_fu_28_ap_return;
        ap_return_1_int_reg <= grp_encrypt_fu_40_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        iv_val_int_reg <= iv_val;
        seed_int_reg <= seed;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = grp_encrypt_fu_28_ap_return;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = grp_encrypt_fu_40_ap_return;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp27) & (1'b1 == ap_ce_reg))) begin
        grp_encrypt_fu_28_ap_ce = 1'b1;
    end else begin
        grp_encrypt_fu_28_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp29) & (1'b1 == ap_ce_reg))) begin
        grp_encrypt_fu_40_ap_ce = 1'b1;
    end else begin
        grp_encrypt_fu_40_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp27 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp29 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp27 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp29 = ~(1'b1 == 1'b1);

assign grp_encrypt_fu_40_key = (iv_val_int_reg + 128'd1);

endmodule //GenerateProof_PRG_1
